-- -------------------------------------------------------------
-- TablePlus 6.8.0(654)
--
-- https://tableplus.com/
--
-- Database: indiancities
-- Generation Time: 2026-01-26 12:56:00.2580
-- -------------------------------------------------------------


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


DROP TABLE IF EXISTS `cache`;
CREATE TABLE `cache` (
  `key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `value` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cache_locks`;
CREATE TABLE `cache_locks` (
  `key` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `owner` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`),
  KEY `cache_locks_expiration_index` (`expiration`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `carousel_items`;
CREATE TABLE `carousel_items` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `subtitle` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `icon` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `order` int NOT NULL DEFAULT '0',
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `cities`;
CREATE TABLE `cities` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci,
  `meta_title` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_description` text COLLATE utf8mb4_unicode_ci,
  `meta_keywords` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `visible_on_homepage` tinyint(1) NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `cities_name_unique` (`name`),
  UNIQUE KEY `cities_slug_unique` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `city_histories`;
CREATE TABLE `city_histories` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `city_id` bigint unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `city_histories_city_id_foreign` (`city_id`),
  CONSTRAINT `city_histories_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `migrations`;
CREATE TABLE `migrations` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `news`;
CREATE TABLE `news` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `city_id` bigint unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_link` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `source_name` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `published_date` timestamp NULL DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `news_city_id_foreign` (`city_id`),
  CONSTRAINT `news_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=101 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `password_reset_tokens`;
CREATE TABLE `password_reset_tokens` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_reset_tokens_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `places`;
CREATE TABLE `places` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `city_id` bigint unsigned NOT NULL,
  `category_id` bigint unsigned DEFAULT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `image` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `published_date` timestamp NULL DEFAULT NULL,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `places_city_id_foreign` (`city_id`),
  KEY `places_category_id_foreign` (`category_id`),
  CONSTRAINT `places_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `place_categories` (`id`) ON DELETE SET NULL,
  CONSTRAINT `places_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=24 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions` (
  `id` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `user_id` bigint unsigned DEFAULT NULL,
  `ip_address` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text COLLATE utf8mb4_unicode_ci,
  `payload` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `last_activity` int NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `videos`;
CREATE TABLE `videos` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `city_id` bigint unsigned NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `youtube_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` longtext COLLATE utf8mb4_unicode_ci,
  `status` tinyint(1) NOT NULL DEFAULT '1',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `videos_city_id_foreign` (`city_id`),
  CONSTRAINT `videos_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `carousel_items` (`id`, `title`, `subtitle`, `image`, `icon`, `link`, `order`, `status`, `created_at`, `updated_at`) VALUES
(1, NULL, NULL, 'carousel/b0Vf52i5ZTW03UBxPd1omwyTaXjlgLILTEojm96O.jpg', NULL, NULL, 1, 1, '2025-12-09 09:29:22', '2025-12-09 10:26:44'),
(2, NULL, NULL, 'carousel/Bxd0W5fYlL51xUiNbn10rsXzwH4ljlYRmRbI3uSM.jpg', NULL, NULL, 2, 1, '2025-12-09 09:29:41', '2025-12-09 10:26:44'),
(3, NULL, NULL, 'carousel/Np8bNUyyLECeJX7ZKmv3povUpWxjPOL63ubzlNQM.jpg', NULL, NULL, 0, 1, '2025-12-09 10:18:38', '2025-12-09 10:26:44'),
(5, NULL, NULL, 'carousel/3vgJ9u1vEHmCq4sMdYRdxaiBJwgVMEm6P4rpmiFl.jpg', NULL, NULL, 4, 1, '2025-12-09 10:27:06', '2025-12-09 10:27:06'),
(6, NULL, NULL, 'carousel/D2ZJmTJHU7Oe7ACarOzG1Vbt86whKdPFiQFNGBHJ.jpg', NULL, NULL, 5, 1, '2025-12-12 09:54:08', '2025-12-12 09:54:08');

INSERT INTO `cities` (`id`, `name`, `slug`, `image`, `description`, `meta_title`, `meta_description`, `meta_keywords`, `status`, `visible_on_homepage`, `created_at`, `updated_at`) VALUES
(1, 'लखनऊ', 'lkhanauu', 'cities/y88ZR5sHoN6aXwtMLYefqNagpOqSI4Ul2wjApGfl.jpg', 'लखनऊ, जिसे \'नवाबों का शहर\' कहते हैं, अपनी \'लखनवी तहजीब\', चिकनकारी कला और शानदार व्यंजनों (जैसे कबाब, बिरयानी, बास्केट चाट) के लिए मशहूर है, यहाँ बड़ा इमामबाड़ा की भूलभुलैया और रूमी दरवाजा जैसी ऐतिहासिक धरोहरें हैं, गोमती नदी के किनारे बसा है और भारत के स्वतंत्रता संग्राम में इसका अहम योगदान रहा है।', NULL, NULL, NULL, 1, 1, '2025-12-09 07:59:01', '2025-12-09 09:53:58'),
(2, 'आगरा', 'aagara', 'cities/HIjvtpbwCh1VnGQ71GVebMVbd2WTOE9IGQDKF9vJ.jpg', 'आगरा उत्तर प्रदेश का एक ऐतिहासिक और सांस्कृतिक रूप से समृद्ध शहर है, जो ताजमहल के कारण विश्वभर में प्रसिद्ध है। मुगल काल की अनगिनत धरोहरें यहाँ की शान बढ़ाती हैं, जिनमें आगरा किला और फ़तेहपुर सीकरी प्रमुख हैं। यमुना नदी के किनारे बसा यह शहर अपनी अद्भुत स्थापत्य कला और सौंदर्य के लिए पर्यटकों को आकर्षित करता है। आगरा की पेठा मिठाई और शहर की खास मंजिलें हर आगंतुक के अनुभव को यादगार बना देती हैं। समृद्ध इतिहास, अनोखी वास्तुकला और जीवंत बाज़ारों ने इसे पर्यटन का प्रमुख केंद्र बना दिया है।\r\nऐसी ही रोचक खबरें पढ़ने के लिए क्लिक करें।', NULL, NULL, NULL, 1, 1, '2025-12-09 08:00:31', '2025-12-09 09:59:49'),
(3, 'कानपुर', 'kanapara', 'cities/cFRRHwmSqxAWFWjRe2zWrJ3hFpvVjIfYGHkM7KKF.jpg', 'कानपुर की 7 सबसे अच्छी घूमने की जगहों में मोती झील, नाना राव पार्क, जंगलेश्वर मंदिर, ब्लू वर्ल्ड थीम पार्क, इस्कॉन मंदिर, फूलबाग और कानपुर ज़ू प्रमुख हैं। ये स्थान प्राकृतिक सुंदरता, इतिहास और मनोरंजन का बेहतरीन मिश्रण पेश करते हैं, जहाँ हर उम्र के लोग कुछ न कुछ खास अनुभव कर सकते हैं।\r\nऐसी ही रोचक खबरें पढ़ने के लिए क्लिक करें।', NULL, NULL, NULL, 1, 1, '2025-12-09 08:39:00', '2025-12-09 10:07:14');

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(1, '0001_01_01_000000_create_cities_table', 1),
(2, '0001_01_01_000001_create_city_histories_table', 1),
(3, '0001_01_01_000002_create_news_table', 1),
(4, '0001_01_01_000003_create_videos_table', 1),
(5, '0001_01_01_000004_create_users_table', 2),
(6, '0001_01_01_000005_create_password_reset_tokens_table', 3),
(7, '0001_01_01_000006_create_sessions_table', 4),
(8, '2025_12_09_000000_add_visible_on_homepage_to_cities_table', 5),
(9, '2025_12_09_000001_create_carousel_items_table', 6),
(10, '2025_12_09_000002_add_seo_fields_to_cities_table', 7),
(11, '2026_01_18_135353_create_cache_table', 8),
(12, '2026_01_24_000007_create_places_table', 9),
(13, '2026_01_24_000008_create_place_categories_table', 9),
(14, '2026_01_24_000009_update_places_add_category_id', 9);

INSERT INTO `news` (`id`, `city_id`, `title`, `description`, `image`, `source_link`, `source_name`, `published_date`, `status`, `created_at`, `updated_at`) VALUES
(1, 1, 'संघ के 100 साल: विभाजन से 1984 दंगों तक संघ का जोर सिखों से मजबूत रिश्तों पर रहा', 'देश के विभाजन के पूर्व अमृतसर में हिंसा हो रही थी. दंगाई सिखों को निशाना बना रहे थे. ऐसे नाजुक मौके पर स्वयंसेवकों ने पंजाब में गुरुद्वारों और सिखों की रक्षा की. इसके लिए दंगाइयों से कई जगहों पर उनका टकराव हुआ.  RSS के 100 सालों के सफर की 100 कहानियों की कड़ी …', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/69732c0e7707d-rss-news-230632923-16x9.jpg', 'https://www.aajtak.in/india/news/story/sangh-100-years-rss-sikh-antio-sikh-riot-1984-partition-india-ntcppl-dskc-2446779-2026-01-23', 'Aajtak.in', '2026-01-23 08:13:46', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(2, 1, 'Kashmir Snowfall: कश्मीर घाटी में भारी बर्फबारी, श्रीनगर एयरपोर्ट पर उड़ानें रद्द, एयरलाइंस ने जारी की एडवाइजरी', 'कश्मीर घाटी में शुक्रवार को हुई भारी बर्फबारी ने हवाई यात्रा को बाधित कर दिया, जिसके चलते श्रीनगर एयरपोर्ट पर कई फ्लाइट स्थगित और रद्द करनी पड़ीं और एयरलाइंस को यात्रियों के लिए ट्रैवल एडवाइजरी जारी करनी पड़ी। श्रीनगर एयरपोर्ट के अधिकारियों ने कहा कि खराब मौस…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Kashmir-Snowfall.jpg', 'https://hindi.moneycontrol.com/india/heavy-snowfall-in-kashmir-valley-flights-cancelled-at-srinagar-airport-airlines-issue-advisory-article-2348450.html', 'Moneycontrol', '2026-01-23 04:31:49', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(3, 1, '23 और 26 जनवरी को इन 6 मेट्रो स्टेशनों के गेट रहेंगे बंद, DMRC ने किया ऐलान', 'Delhi Metro January 2026: गणतंत्र दिवस की तैयारियों को देखते हुए राजधानी में सुरक्षा के कड़े इंतजाम किए गए हैं। जिसको देखते हुए दिल्ली मेट्रो रेल कॉरपोरेशन (DMRC) ने 23 और 26 जनवरी 2026 को सुबह 3 बजे से कार्यक्रम खत्म होने तक 6 मेट्रो स्टेशनों के चुनिंदा गेट …', 'https://images.moneycontrol.com/static-hindinews/2026/01/DMRC.jpg', 'https://hindi.moneycontrol.com/india/the-gates-of-these-six-metro-stations-will-remain-closed-on-january-23-and-26-dmrc-announced-article-2348355.html', 'Moneycontrol', '2026-01-23 03:59:50', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(4, 1, 'UP Diwas 2026: 150 फीट ऊंची वंदे मातरम पेंटिंग बनेगी यूपी दिवस की शान, कई कार्यक्रम भी होंगे आयोजित', 'UP Diwas 2026: 24 से 26 जनवरी तक चलने वाले तीन दिवसीय उत्तर प्रदेश दिवस समारोह के दौरान राष्ट्रीय प्रेरणा स्थल पर विभिन्न राज्य एजेंसियों द्वारा कई प्रदर्शनियों और सांस्कृतिक कार्यक्रमों का आयोजन किया जाएगा। उत्तर प्रदेश राज्य ललित कला अकादमी, ललित कला अकादमी…', 'https://images.moneycontrol.com/static-hindinews/2026/01/UP-Diwas.jpg', 'https://hindi.moneycontrol.com/india/150-feet-high-vande-mataram-painting-will-be-the-pride-of-up-day-many-programs-will-also-be-organized-article-2348268.html', 'Moneycontrol', '2026-01-23 03:14:55', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(5, 1, 'इन उम्मीदवारों के लिए नौकरी का शानदार मौका, मेडिकल फील्ड में इस पद पर बना सकते हैं करियर', 'ESIC ने इंश्योरेंस मेडिकल ऑफिसर (IMO) ग्रेड-II के 225 पदों पर MBBS पास उम्मीदवारों का आवेदन मांगा है. ऐसे में जो भी उम्मीदवार इस पद पर आवेदन करना चाहते हैं, वे ऑफिशियल वेबसाइट पर जाकर सारी डिटेल ले सकते हैं.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/6971f329572c1-esic-imo-2026-225131496-16x9.jpg', 'https://www.aajtak.in/education/career/story/esic-imo-2026-job-update-mbbs-pass-candidate-can-apply-ngix-dskc-2446035-2026-01-23', 'Aajtak.in', '2026-01-23 02:25:33', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(6, 1, 'Delhi Weather Update: IMD का येलो अलर्ट, दिल्ली में आज तेज हवाओं और गरज के साथ बारिश की संभावना, AQI में हो सकता है सुधार', 'Delhi Weather Update: शुक्रवार को दिल्ली के कुछ हिस्सों में हल्की बारिश दर्ज की गई। भारत मौसम विज्ञान विभाग (IMD) ने सक्रिय पश्चिमी विक्षोभ के कारण और अधिक बारिश की चेतावनी दी है। IMD के अनुसार, सुबह से दोपहर के बीच एक या दो बार हल्की बारिश होने की संभावना है…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-weather-1.jpg', 'https://hindi.moneycontrol.com/india/imd-issues-yellow-alert-delhi-likely-to-experience-strong-winds-and-thunderstorms-today-aqi-likely-to-improve-article-2348128.html', 'Moneycontrol', '2026-01-23 02:14:52', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(7, 1, 'बसंत पंचमी पर बदला मौसम, नॉर्थ इंडिया में बारिश तो कश्मीर में बर्फबारी, फ्लाइट्स पर असर', 'Delhi-NCR Weather Today Live: बसंत पंचमी पर दिल्ली-एनसीआर समेत उत्तर भारत के कई राज्यों में मौसम का मिजाज बदला है. दिल्ली, गुरुग्राम, फरीदाबाद, नोएडा, गाजियाबाद, मेरठ समेत एनसीआर में सुबह-सुबह बूंदाबांदी और हल्की बारिश हुई है. IMD के मुताबिक, उत्तर भारत में ह…', 'https://akm-img-a-in.tosshub.com/aajtak/images/breaking_news/202601/6972dad8ce286-weather-update-232003663-16x9.jpeg', 'https://www.aajtak.in/india/news/story/weather-forecast-today-23-january-basant-anchmi-delhi-ncr-rain-heavy-snowfall-kashmir-mountains-imd-mausam-szlbs-2446424-2026-01-23', 'Aajtak.in', '2026-01-23 02:13:20', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(8, 1, 'Delhi: रेखा गुप्ता सरकार का साल पूरा होने को आया, महिलाओं को ₹2,500 का इंतजार, अधर में महिला समृद्धि योजना!', 'दिल्ली में रेखा गुप्ता के नेतृत्व वाली बीजेपी सरकार को एक साल पूरा होने में एक महीने से भी कम समय बचा है। लेकिन राष्ट्रीय राजधानी की महिलाएं अभी भी भाजपा के बड़े चुनावी वादों में से एक का इंतजार कर रही हैं – महिला समृद्धि योजना के तहत 2,500 रुपए की मासिक सहाय…', 'https://images.moneycontrol.com/static-hindinews/2025/03/Rekha-Gupta-Delhi-CM.jpg', 'https://hindi.moneycontrol.com/india/delhi-rekha-gupta-government-year-is-about-to-complete-women-waiting-for-2500-rs-mahila-samriddhi-yojana-hanging-in-balance-article-2348141.html', 'Moneycontrol', '2026-01-23 02:06:30', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(9, 1, 'Delhi Pollution: दिल्ली- NCR की एयर क्वालिटी में सुधार, GRAP-3 की पाबंदियां खत्म, इन चीजों से हटा बैन', 'Delhi Pollution: दिल्ली-NCR में एयर क्वालिटी में सुधार होने के कारण कमीशन फॉर एयर क्वालिटी मैनेजमेंट (CAQM) ने GRAP-3 की पाबंदियां हटा दी हैं। एयर क्वालिटी इंडेक्स (AQI) में सुधार के साथ कंस्ट्रक्शन और ट्रैफिक पर लगी पाबंदियों में अब ढील दी गई है। CAQM ने गुर…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-AQI-404-Struggles-with-Poor-Visibility.jpg', 'https://hindi.moneycontrol.com/india/delhi-pollution-air-quality-improves-in-ncr-grap-3-restrictions-lifted-ban-removed-on-these-activities-article-2348039.html', 'Moneycontrol', '2026-01-22 15:00:31', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(10, 1, 'Moradabad: मुस्लिम लड़के और उसकी हिंदू प्रेमिका की हत्या कर शफ दफनाया, लड़की के भाइयों ने वारदात को दिया अंजाम', 'उत्तर प्रदेश के मुरादाबाद से सामने आया यह मामला इंसानियत को झकझोर देने वाला है। इज्जत के नाम पर की गई इस खौफनाक हत्या में एक 27 साल के मुस्लिम युवक और उसकी 22 साल की हिंदू प्रेमिका को बेरहमी से मौत के घाट उतार दिया गया। आरोप है कि लड़की के ही भाइयों ने दोनों …', 'https://images.moneycontrol.com/static-hindinews/2026/01/Moradabad-Double-Murder.jpg', 'https://hindi.moneycontrol.com/india/moradabad-muslim-boy-and-his-hindu-girlfriend-murdered-and-buried-girl-s-brothers-carried-out-the-crime-article-2347458.html', 'Moneycontrol', '2026-01-22 08:40:36', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(11, 1, 'छत्तीसगढ़ के स्टील प्लांट में बड़ा हादसा, कोयला भट्ठे में विस्फोट से 6 मजूदरों की मौत, कई झुलसे', 'Chhattisgarh Steel Plant Blast: छत्तीसगढ़ के बलोदा बाजार-भाटापारा जिले में गुरुवार को एक स्टील प्लांट में कोयला भट्ठे में विस्फोट होने से छह श्रमिकों की मौत हो गई और चार अन्य गंभीर रूप से घायल हो गए। विस्फोट के बाद बड़े पैमाने पर बचाव अभियान चलाया गया है और आ…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Chhattisgarh-1.jpg', 'https://hindi.moneycontrol.com/india/major-accident-at-chhattisgarh-steel-plant-6-workers-killed-several-injured-in-coal-furnace-explosion-article-2347380.html', 'Moneycontrol', '2026-01-22 08:03:41', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(12, 1, '1984 Anti-Sikh Riots: जनकपुरी-विकासपुरी हिंसा मामले में सज्जन कुमार को मिली राहत, अदालत ने किया बरी', '1984 Anti-Sikh Riots: दिल्ली की एक अदालत ने गुरुवार को पूर्व कांग्रेस नेता सज्जन कुमार को 1984 में जनकपुरी और विकासपुरी में हुए सिख विरोधी दंगों से संबंधित मामले में बरी कर दिया। इन दंगों में दो लोगों की मौत हो गई थी। राउज एवेन्यू कोर्ट ने कहा कि अभियोजन पक्ष…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Sajjan-kumar.jpg', 'https://hindi.moneycontrol.com/india/sajjan-kumar-gets-relief-in-janakpuri-vikaspuri-violence-case-court-acquits-him-article-2347233.html', 'Moneycontrol', '2026-01-22 06:27:06', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(13, 1, 'Delhi Crime News: दिल्ली में चाकू गोदकर युवक की बेरहमी से हत्या, CCTV में कैद हुई खौफनाक वारदात', 'Delhi Crime News: राष्ट्रीय राजधानी दिल्ली में लगभग हर दिन किसी न किसी इलाके से सनसनीखेज वारदात सामने आ रही है, जिसने आम लोगों की सुरक्षा को लेकर गंभीर सवाल खड़े कर दिए हैं। ताजा मामला दिल्ली के मंगोलपुरी इलाके से सामने आई है। यहां चाकूबाजी में एक युवक की बदम…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-Crime.jpg', 'https://hindi.moneycontrol.com/india/a-young-man-was-brutally-stabbed-to-death-in-delhi-the-horrific-incident-was-captured-on-cctv-article-2347160.html', 'Moneycontrol', '2026-01-22 05:41:06', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(14, 1, 'Delhi Air Pollution: दिल्ली में वायु गुणवत्ता \'बहुत खराब\', GRAP स्टेज 1-3 लागू, IMD ने बिजली गिरने और तेज हवाओं का लगाया पूर्वानुमान', 'Delhi Air Pollution: केंद्रीय प्रदूषण नियंत्रण बोर्ड (CPCB) के आंकड़ों के अनुसार, गुरुवार को दिल्ली की वायु गुणवत्ता \'बहुत खराब\' श्रेणी में बनी रही, जहां 24 घंटे का औसत एयर क्वालिटी इंडेक्स (AQI) 330 दर्ज किया गया। वहीं, गुरुवार सुबह 8 बजे दिल्ली का AQI 312 द…', 'https://images.moneycontrol.com/static-hindinews/2026/01/GRAP.jpg', 'https://hindi.moneycontrol.com/india/delhi-air-quality-very-poor-grap-stage-1-3-imposed-imd-forecasts-lightning-and-strong-winds-article-2347000.html', 'Moneycontrol', '2026-01-22 04:40:59', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(15, 1, 'Delhi Parking Charges Doubled: दिल्ली सरकार ने GRAP 3 और 4 के तहत पार्किंग फीस की दोगुनी, निजी वाहनों के उपयोग को कम करने का लिया फैसला', 'Delhi Parking Charges Doubled: दिल्ली सरकार ने बुधवार को अधिकृत पार्किंग स्थलों पर मौजूदा पार्किंग शुल्क को दोगुना करने का निर्णय लिया है, ताकि GRAP स्टेज III - \'गंभीर\' वायु गुणवत्ता (AQI 401-450 के बीच) और GRAP स्टेज IV - \'गंभीर से अधिक\' वायु गुणवत्ता (AQI 4…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-pollution.jpg', 'https://hindi.moneycontrol.com/india/delhi-government-decides-to-double-parking-fees-under-grap-3-and-4-to-reduce-the-use-of-private-vehicles-article-2346905.html', 'Moneycontrol', '2026-01-22 03:51:29', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(16, 1, 'दिल्ली और गुरुग्राम पुलिस ने 22 जनवरी के लिए जारी की ट्रैफिक एडवाइजरी, जाम से बचने के लिए आपनाएं ये मार्ग', 'Delhi Gurugram Traffic News: दिल्ली ट्रैफिक पुलिस ने बुधवार को बताया कि विजय चौक पर बीटिंग रिट्रीट समारोह के रिहर्सल के कारण 22 जनवरी को नई दिल्ली के कुछ हिस्सों में यातायात प्रतिबंध लागू रहेंगे। इसी बीच, गुरुग्राम ट्रैफिक पुलिस ने गणतंत्र दिवस समारोह से पहले…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Traffic-advisory-1.jpg', 'https://hindi.moneycontrol.com/india/delhi-and-gurugram-police-have-issued-a-traffic-advisory-for-january-22-take-these-routes-to-avoid-traffic-jams-article-2346645.html', 'Moneycontrol', '2026-01-22 02:05:39', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(17, 1, 'Gold Price Record High Silver Price Delhi Bullion Market Rally Safe Haven Assets Us-eu Tension Greenland', 'Gold Silver Price: सोने की कीमतें 1.60 लाख रुपये/10 ग्राम के करीब और चांदी 3.34 लाख रुपये/किलोग्राम के रिकॉर्ड स्तर पर पहुंच गई हैं। अमेरिका-ईयू तनाव और रुपये की कमजोरी के कारण बुलियन मार्केट में भारी उछाल। पढ़ें पूरी रिपोर्ट।', 'https://staticimg.amarujala.com/assets/images/2026/01/21/gold-silver-price-today_b5e3e4743996d05da93206e25998e4ac.gif?w=750&dpr=1.0', 'https://www.amarujala.com/business/bazaar/gold-price-record-high-silver-price-delhi-bullion-market-rally-safe-haven-assets-us-eu-tension-greenland-2026-01-21', 'Amarujala.com', '2026-01-21 13:44:51', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(18, 1, 'Gurugram Gang Rape Case: स्पा में नशीली दवा देकर महिला के साथ गैंगरेप, पार्टनर समेत दो आरोपी फरार', 'Gurugram Gang Rape Case: एक भयावह घटना में, दिल्ली की 29 वर्षीय महिला के साथ इस महीने की शुरुआत में एक स्पा सेंटर में उसके साथी समेत दो पुरुषों ने कथित तौर पर नशीली दवा देकर सामूहिक बलात्कार किया। गुरुग्राम पुलिस ने भारतीय न्याय संहिता की धारा 70(1) के तहत आर…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Gurugram.jpg', 'https://hindi.moneycontrol.com/india/woman-drugged-and-gang-raped-at-spa-two-accused-including-partner-absconding-article-2346004.html', 'Moneycontrol', '2026-01-21 07:16:14', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(19, 1, 'Delhi Viral Video News: गाड़ी पर \"Dawood\" लिखवाकर लापरवाही से ड्राइविंग करने का वीडियो वायरल, पुलिस ने लिया एक्शन, जानें क्या है पूरा मामला', 'Delhi Viral Video News: दिल्ली पुलिस ने मंगलवार को 21 वर्षीय एक युवक को गिरफ्तार किया और एफआईआर दर्ज की। यह कार्रवाई उत्तरी दिल्ली की एक व्यस्त सड़क पर लापरवाही से वाहन चलाते हुए एक वीडियो के सोशल मीडिया पर वायरल होने के बाद की गई। वीडियो में देखा जा सकता है …', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-viral-news.jpg', 'https://hindi.moneycontrol.com/india/video-of-a-reckless-driver-with-dawood-written-on-his-car-goes-viral-police-take-action-learn-the-full-story-article-2345923.html', 'Moneycontrol', '2026-01-21 06:34:05', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(20, 1, 'Delhi Road Projects 2026: दिल्ली में जाम की समस्या होगी खत्म, इन रोड पर बनेंगे तीन नए फ्लाईओवर, सरकार ने दी मंजूरी', 'Delhi Road Projects 2026: दिल्ली सरकार ने शहर में यातायात की भीड़ कम करने के लिए तीन सड़क परियोजनाओं को वित्तीय मंजूरी दे दी है। लोक निर्माण विभाग (पीडब्ल्यूडी) मंत्री परवेश साहिब सिंह ने मंगलवार को यह जानकारी दी। बता दें कि सरकार जनकपुरी-पंखा रोड पर एक नया फ…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-traffic.jpg', 'https://hindi.moneycontrol.com/india/the-problem-of-traffic-jam-in-delhi-will-end-three-new-flyovers-will-be-built-on-these-roads-the-government-has-given-approval-article-2345640.html', 'Moneycontrol', '2026-01-21 04:18:01', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(21, 1, 'Delhi AQI: दिल्ली में सांस लेना हुआ मुश्किल, AQI पहुंचा 343, GRAP-4 लागू', 'Delhi AQI: केंद्रीय प्रदूषण नियंत्रण बोर्ड (CPCB) के समीर ऐप के आंकड़ों के अनुसार, बुधवार को सुबह 6:05 बजे दिल्ली का वायु गुणवत्ता सूचकांक (AQI) 343 रहा, जो \'बहुत खराब\' श्रेणी में बना हुआ है। हालांकि, मौसम में थोड़ा बदलाव देखा गया। NCR में पड़ रही तेज ठंड में…', 'https://images.moneycontrol.com/static-hindinews/2026/01/AQI-2.jpg', 'https://hindi.moneycontrol.com/india/breathing-becomes-difficult-in-delhi-aqi-reaches-343-grap-4-implemented-article-2345456.html', 'Moneycontrol', '2026-01-21 02:10:21', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(22, 1, 'Viral Video: व्यस्त नेशनल हाईवे पर SUV से खतरनाक स्टंटबाजी, वीडियो वायरल होने पर एक्शन में आई दिल्ली पुलिस', 'SUV Viral Video: दिल्ली पुलिस ने राजधानी में नेशनल हाईवे-48 के एक व्यस्त हिस्से पर लापरवाही से गाड़ी चलाने के आरोप में 21 साल के एक युवक को गिरफ्तार किया है। साथ ही उसकी SUV जब्त कर ली है। यह कार्रवाई सोशल मीडिया पर एक वीडियो सामने आने के बाद हुई। इसमें नरेला…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-cops-arrest-old.jpg', 'https://hindi.moneycontrol.com/india/viral-video-dangerous-stunts-performed-from-an-suv-on-a-busy-highway-delhi-police-action-cops-arrest-article-2345388.html', 'Moneycontrol', '2026-01-20 14:40:57', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(23, 1, 'Delhi AQI: दिल्ली-NCR में GRAP-4 की पाबंदियां हटाई गई, एयर क्वालिटी में मामूली सुधार के बाद फैसला', 'Delhi Air Quality: कमीशन फॉर एयर क्वालिटी मैनेजमेंट (CAQM) ने मंगलवार (20 जनवरी) को एयर क्वालिटी में मामूली सुधार के बाद दिल्ली-NCR में GRAP-4 की पाबंदियों को हटाने की घोषणा की है। मंगलवार को दिल्ली का एयर क्वालिटी इंडेक्स (AQI) 378 दर्ज किया गया। फिलहाल, AQI…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-Air-Quality_.jpg', 'https://hindi.moneycontrol.com/india/delhi-aqi-grap-4-restrictions-lifted-in-delhi-ncr-after-a-slight-improvement-in-air-quality-article-2345379.html', 'Moneycontrol', '2026-01-20 13:50:44', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(24, 1, '\'दाऊद\' लिखी स्कॉर्पियो के साथ दिल्ली पुलिस ने युवक को दबोचा, गाड़ी जब्त', 'Delhi Police Action against Scorpio N: दिल्ली पुलिस ने NH-48 पर लापरवाही से स्कॉर्पियो-एन चलाने वाले दाऊद अंसारी को गिरफ्तार किया है. सोशल मीडिया पर जिग-जैग ड्राइविंग का वीडियो वायरल होने के बाद समयपुर बादली थाने में केस दर्ज किया गया.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/696f6048d3359-delhi-police-arrest-scorpio-stunt-nh-48-200019248-16x9.jpg', 'https://www.aajtak.in/india/delhi/story/delhi-police-arrest-dawood-ansari-scorpio-stunt-nh48-gtk-karnal-bypass-lcln-rpti-2444137-2026-01-20', 'Aajtak.in', '2026-01-20 11:04:31', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(25, 1, 'Nitin Nabin: नितिन नबीन बने भारतीय जनता पार्टी के राष्ट्रीय अध्यक्ष, पीएम बोलें- BJP में हुआ \'नबीन\' युग का आगाज', 'Nitin Nabin: भारतीय जनता पार्टी (BJP) ने आज को नितिन नबीन को पार्टी का नया राष्ट्रीय अध्यक्ष नियुक्त किया है। प्रधानमंत्री नरेंद्र मोदी, गृह मंत्री अमित शाह और रक्षा मंत्री राजनाथ सिंह की मौजूदगी में नबीन ने कार्यभार संभाला। 45 वर्षीय नितिन नबीन भाजपा के 12वे…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Nitin-Nabin-took-charge-as-the-BJP-national-president.jpg', 'https://hindi.moneycontrol.com/india/nitin-nabin-took-charge-as-the-bjp-national-president-bjp-gets-its-new-chief-pm-modi-ushers-in-nabin-era-article-2344686.html', 'Moneycontrol', '2026-01-20 06:34:24', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(26, 1, 'Etah Family Murder: एटा में दिल दहला देने वाली वारदात, एक ही परिवार के 4 लोगों की बेरहमी से हत्या, इलाके में सनसनी', 'Etah Family Murder: सोमवार दोपहर को एटा जिला मुख्यालय के मोहल्ला नगला प्रेमी इलाके में एक परिवार के चार सदस्यों की अज्ञात हमलावरों ने उनके घर में बेरहमी से हत्या कर दी। 75 वर्षीय गंगा सिंह, उनकी 70 वर्षीय पत्नी श्यामा देवी, 42 वर्षीय बहू रत्ना और 23 वर्षीय पो…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Etah.jpg', 'https://hindi.moneycontrol.com/india/a-shocking-incident-in-etah-where-four-members-of-a-family-were-brutally-murdered-after-entering-their-house-article-2344556.html', 'Moneycontrol', '2026-01-20 05:22:15', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(27, 1, 'Delhi Metro Urination Video: दिल्ली मेट्रो स्टेशन के अंदर पेशाब करते व्यक्ति का वीडियो वायरल, लोगों ने की जमकर आलोचना', 'Delhi Metro Urination Video: दिल्ली मेट्रो स्टेशन के अंदर पेशाब करते हुए एक व्यक्ति का वीडियो सोशल मीडिया पर वायरल हो गया है, जिससे लोगों में व्यापक आक्रोश फैल गया है। कई लोग इस कृत्य की निंदा करते हुए इसे नागरिक जिम्मेदारी में गिरावट और सार्वजनिक स्वच्छता की…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-metro.jpg', 'https://hindi.moneycontrol.com/india/video-of-man-urinating-inside-delhi-metro-station-goes-viral-draws-criticism-article-2344483.html', 'Moneycontrol', '2026-01-20 04:36:03', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(28, 1, 'Delhi AQI: NCR में जहरीली हवा का पहरा, गाजियाबाद देश का सबसे प्रदूषित शहर; दिल्ली-नोएडा में भी AQI 400 पार', 'Delhi AQI Today: दिल्ली-एनसीआर में प्रदूषण ने एक बार फिर विकराल रूप धारण कर लिया है। सोमवार को देश के 10 सबसे प्रदूषित शहरों की सूची में सभी शहर एनसीआर के रहे। लगातार दूसरे दिन गाजियाबाद देश का सबसे प्रदूषित शहर दर्ज किया गया, जबकि नोएडा दूसरे और दिल्ली तीसरे…', 'https://images.moneycontrol.com/static-hindinews/2025/12/Delhi-aqi-Dense-smog.jpg', 'https://hindi.moneycontrol.com/india/delhi-ncr-pollution-ghaziabad-noida-most-polluted-aqi-today-dense-fog-low-visibility-article-2344130.html', 'Moneycontrol', '2026-01-20 02:03:06', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(29, 1, 'India Tariff: भारत के 30 परसेंट टैरिफ से उड़ी अमेरिका की नींद, दौड़े दौड़े अमेरिकी सीनेटर', 'India Tariff on America: अमेरिकी दालों पर भारत का 30 परसेंट टैरिफ लगाने का फैसला अमेरिका को रास नहीं आया क्योंकि भारत दुनिया में दालों का सबसे बड़ा उपभोक्ता है और अमेरिका से इसका आयात भी करता है.', 'https://feeds.abplive.com/onecms/images/uploaded-images/2026/01/19/0a51e1e0edeb45738ca6dfc19ae8832017687918584641160_original.jpg?impolicy=abp_cdn&imwidth=1200', 'https://www.abplive.com/business/us-senator-steve-daines-met-foreign-minister-s-jaishankar-regarding-india-30-percent-tariff-on-american-pulses-3076195', 'Abplive.com', '2026-01-20 01:14:51', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(30, 1, 'अक्टूबर से जनवरी आ गया लेकिन दिल्ली-NCR का पॉल्यूशन नहीं हुआ कंट्रोल? आखिर क्यों', 'अक्टूबर से जनवरी हो गई लेकिन दिल्ली-NCR गैस चेंबर ही बना हुआ है. राजनीतिक इच्छाशक्ति की कमी, नियमों का सही से पालन न होना, वैज्ञानिकों की सलाह न मानना ही इसकी वजह है. AQI अब भी खतरनाक स्तर पर है. सिस्टम लाचार है. GRAP का उल्लघंन आम है. विभागों में समन्वय कम ह…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/696dc26f8fb3a-delhi-ncr-pollution-193433614-16x9.jpg', 'https://www.aajtak.in/science/story/delhi-ncr-pollution-crisis-oct-to-jan-cse-report-analysis-dskc-2442791-2026-01-19', 'Aajtak.in', '2026-01-19 05:43:36', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(31, 1, 'झांसी में मेरठ जैसा \'ब्लू ड्रम\' हत्याकांड, रिटायर्ड रेलवे कर्मचारी ने की प्रेमिका की हत्या, फिर शव को ट्रंक में छुपाया', 'Jhansi: मेरठ के \'ब्लू ड्रम\' हत्याकांड की तरह, एक सेवानिवृत्त रेलवे कर्मचारी ने शनिवार आधी रात के बाद अपनी प्रेमिका की हत्या करने के बाद उसके शव को जला दिया और अवशेषों को एक नीले रंग के ट्रंक में छिपा दिया। यह मामला तब सामने आया जब ट्रंक को ठिकाने लगाने के लिए…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Jhansi-1.jpg', 'https://hindi.moneycontrol.com/india/meerut-like-blue-drum-murder-case-in-jhansi-retired-railway-employee-kills-girlfriend-then-hides-body-in-trunk-article-2343133.html', 'Moneycontrol', '2026-01-19 03:36:54', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(32, 1, 'Delhi-Dehradun Expressway: दिल्ली-देहरादून एक्सप्रेसवे अपने अंतिम चरण में, अब सिर्फ 2.5 घंटे में पूरा होगा सफर', 'Delhi-Dehradun Expressway: दिल्ली-देहरादून ग्रीनफील्ड परियोजना अपने अंतिम चरण में है, और जनता के लिए खोले जाने से पहले केवल कुछ मामूली फिनिशिंग का काम बाकी है। एक बार चालू हो जाने पर, 210 किलोमीटर लंबा यह कॉरिडोर दिल्ली और देहरादून के बीच यात्रा के समय को वर्…', 'https://images.moneycontrol.com/static-hindinews/2026/01/दिल्ली-देहरादून.jpg', 'https://hindi.moneycontrol.com/india/delhi-dehradun-expressway-in-its-final-phase-now-the-journey-will-be-completed-in-just-2-5-hours-article-2343060.html', 'Moneycontrol', '2026-01-19 02:49:44', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(33, 1, 'Delhi AQI: दिल्ली पर \'स्मॉग\' और प्रदूषण की दोहरी मार, AQI 400 के पार; जनवरी में भी लोगों का सांस लेना मुहाल', 'Delhi AQI Today: देश की राजधानी दिल्ली इस समय \'दमघोंटू\' हवा और \'जीरो विजिबिलिटी\' के दोहरे संकट से जूझ रही है। सोमवार सुबह दिल्ली का औसत वायु गुणवत्ता सूचकांक (AQI) 418 दर्ज किया गया, जो \'गंभीर\' श्रेणी में आता है। मौसम विभाग (IMD) ने घने कोहरे को लेकर येलो अलर…', 'https://images.moneycontrol.com/static-hindinews/2025/12/Delhi-AQI-edges-closer-to-severe.jpg', 'https://hindi.moneycontrol.com/india/delhi-ncr-air-quality-pollution-cold-fog-and-aqi-in-very-poor-category-yellow-alert-article-2342997.html', 'Moneycontrol', '2026-01-19 02:45:47', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(34, 1, 'दिल्ली में लग्जरी कार चोरी सिंडिकेट बेनकाब, फॉर्च्यूनर-थार समेत 16 महंगी गाड़ियां बरामद', 'दिल्ली पुलिस ने वाहन चोरी के एक बड़े सिंडिकेट का खुलासा किया है. इस गिरोह के तीन सदस्यों को गिरफ्तार कर 16 महंगी चोरी की गाड़ियां बरामद की गई हैं. दिल्ली और NCR से चोरी की गई गाड़ियों को फर्जी दस्तावेजों के जरिए पंजाब सहित कई राज्यों में बेचने का खेल चल रहा थ…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/696d115ae6a31-delhi-police-busted-vehicle-theft-syndicate-185901174-16x9.jpg', 'https://www.aajtak.in/crime/news/story/delhi-police-busted-interstate-vehicle-theft-syndicate-cars-recovered-opnm2-dskc-2442410-2026-01-18', 'Aajtak.in', '2026-01-18 17:01:38', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(35, 1, 'WhatsApp पर निवेश का झांसा, 14 दिन में 4 करोड़ का खेल... दिल्ली में इन्वेस्टमेंट फ्रॉड रैकेट का पर्दाफाश', 'दिल्ली पुलिस ने साइबर फ्रॉड रैकेट का पर्दाफाश किया है, जिसका कंट्रोल कंबोडिया से किया जा रहा था. ऊंचे रिटर्न का लालच देकर लोगों से करोड़ों की ठगी की गई. म्यूल बैंक खातों के जरिए सिर्फ 14 दिनों में करीब 4 करोड़ रुपए इधर-उधर किए गए. पुलिस ने 8 साइबर ठगों को गिर…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/696ccb2b98a13-interstate-investment-fraud-racket-busted-in-delhi-185934311-16x9.jpg', 'https://www.aajtak.in/crime/cyber-crime/story/interstate-investment-fraud-racket-busted-delhi-police-cyber-criminals-opnm2-dskc-2442280-2026-01-18', 'Aajtak.in', '2026-01-18 15:05:49', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(36, 1, 'Weather Update: दिल्ली-NCR और इन राज्यों में अगले 4 दिन कड़ाके की ठंड और बारिश, IMD का अलर्ट जारी', 'भारत मौसम विज्ञान विभाग (IMD) ने उत्तर और मध्य भारत में सख्त सर्दी लहर और घने कोहरे को देखते हुए ऑरेंज और येलो अलर्ट जारी किए हैं। शनिवार को उत्तराखंड और उत्तर प्रदेश के लिए ऑरेंज अलर्ट लागू किया गया है। इन राज्यों में सुबह और रात के समय बहुत घना कोहरा रहने औ…', 'https://images.moneycontrol.com/static-hindinews/2023/12/Delhifog.jpg', 'https://hindi.moneycontrol.com/india/delhi-ncr-cold-rain-alert-imd-next-4-days-weather-update-north-india-article-2342786.html', 'Moneycontrol', '2026-01-18 04:38:08', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(37, 1, 'Delhi AQI: दिल्ली में जहरीली धुंध के साथ हाड़ कंपाने वाली ठंड का डबल अटैक, फिर से लागू हुआ GRAP-4', 'Delhi AQI Today: रविवार की सुबह दिल्लीवासियों के लिए दोहरी मुसीबत लेकर आई। राजधानी जहरीली धुंध की घनी चादर में लिपटी रही और वायु गुणवत्ता सूचकांक (AQI) गंभीरतम स्तर पर पहुंच गया। आनंद विहार में AQI का स्तर 489 दर्ज किया गया, जो स्वास्थ्य के लिए बेहद खतरनाक है…', 'https://images.moneycontrol.com/static-hindinews/2025/12/Delhi-AQI-Remains-Very-Poor-.jpg', 'https://hindi.moneycontrol.com/india/delhi-aqi-plummets-to-severe-plus-levels-hits-489-in-anand-vihar-as-toxic-smog-shrouds-capital-imd-cold-wave-alert-article-2342733.html', 'Moneycontrol', '2026-01-18 02:02:07', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(38, 1, 'दिल्ली से पटना जा रही राजधानी एक्सप्रेस को बम से उड़ाने की धमकी, 31 मिनट खड़ी रही ट्रेन', 'दिल्ली–पटना तेजस राजधानी को बम से उड़ाने की धमकी ने रेल सुरक्षा तंत्र को अलर्ट पर ला दिया. अलीगढ़ में ट्रेन रोकी गई, बीडीएस से लेकर डॉग स्क्वाड तक ने जांच की. 31 मिनट बाद खतरा टला, लेकिन प्रीमियम ट्रेनों की सुरक्षा को लेकर सवाल फिर खड़े हो गए.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/696bf8fcc3523-rajdhani-express-17024785-16x9.jpg', 'https://www.aajtak.in/india/news/story/rajdhani-express-delhi-to-patna-bomb-threat-tejas-rajdhani-ntc-vhrw-dskc-2441865-2026-01-18', 'Aajtak.in', '2026-01-17 21:04:50', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(39, 1, 'Delhi GRAP-4: दिल्ली का AQI 400 के पार, फिर लागू हुआ GRAP-4, हवा हुई जहरीली!', 'दिल्ली-NCR में बढ़ते प्रदूषण को देखते हुए एक बार फिर सबसे सख्त पाबंदियां लागू कर दी गई हैं। हवा की क्वालिटी यानी AQI तेजी से बढ़ते हुए 450 के करीब पहुंच गई है, जिसे ‘Severe+’ यानी बेहद गंभीर कैटेगरी में रखा जाता है।वायु गुणवत्ता प्रबंधन आयोग (CAQM) ने बताया क…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-AQI-1.jpg', 'https://hindi.moneycontrol.com/india/delhi-ncr-grap-4-aqi-crosses-400-air-pollution-becomes-poisonous-article-2342678.html', 'Moneycontrol', '2026-01-17 15:44:07', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(40, 1, 'भारत में अमेरिकी दालों पर आयात शुल्क कम करने की उठी मांग, ट्रेड डील में कृषि क्षेत्र बन रही बड़ी बाधा!', 'India-US Trade Deal: भारत और अमेरिका के बीच ट्रेड डील को लेकर बातचीत जारी है। इसी बीच अमेरिकी सीनेटरों ने राष्ट्रपति डोनाल्ड ट्रंप से भारत द्वारा दालों पर लगाए गए 30% आयात शुल्क को हटवाने की अपील की है। यानी की भारत में आने वाली अमेरिकी दालों पर टैरिफ कम करने…', 'https://images.moneycontrol.com/static-hindinews/2026/01/US-seek-tariff-relief-on-Indian-pulse.jpg', 'https://hindi.moneycontrol.com/india/us-lawmakers-push-trump-to-seek-tariff-relief-on-indian-pulse-imports-article-2342446.html', 'Moneycontrol', '2026-01-17 09:29:40', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(41, 1, 'PM Modi Malda Visit: PM मोदी आज मालदा में वंदे भारत स्लीपर ट्रेन को दिखाएंगे हरी झंडी, जनसभा को भी करेंगे संबोधित', 'PM Modi Malda Visit: प्रधानमंत्री नरेंद्र मोदी शनिवार सुबह मालदा का दौरा करेंगे और देश की पहली वंदे भारत स्लीपर ट्रेन को हरी झंडी दिखाएंगे, जो बंगाल के हावड़ा और असम के कामाख्या को जोड़ेगी। इसके साथ ही उत्तर बंगाल और उत्तर पूर्व को दक्षिण भारत से जोड़ने वाली …', 'https://images.moneycontrol.com/static-hindinews/2026/01/PM-Modi-1.jpg', 'https://hindi.moneycontrol.com/india/pm-modi-will-flag-off-the-vande-bharat-sleeper-train-in-malda-today-and-will-also-address-a-public-rally-article-2342327.html', 'Moneycontrol', '2026-01-17 03:28:39', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(42, 1, 'Delhi AQI: राजधानी में सांस लेना हुआ मुश्किल, AQI पहुंचा 364, कई इलाकों में ‘गंभीर’ हालात', 'Delhi AQI: केंद्रीय प्रदूषण नियंत्रण बोर्ड (CPCB) के SAMEER ऐप से प्राप्त आंकड़ों के अनुसार, शनिवार सुबह राष्ट्रीय राजधानी में वायु गुणवत्ता \"बहुत खराब\" श्रेणी में बनी रही। सुबह 5:05 बजे एयर क्वालिटी इंडेक्स (AQI) 364 दर्ज किया गया। शुक्रवार को दिल्ली का AQI …', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-AQI-2.jpg', 'https://hindi.moneycontrol.com/india/breathing-became-difficult-in-the-capital-aqi-reached-364-situation-was-serious-in-many-areas-article-2342316.html', 'Moneycontrol', '2026-01-17 02:26:04', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(43, 1, 'Delhi Weather Update: घने कोहरे और शीत लहर से कांपी दिल्ली, न्यूनतम तापमान 4.3°C पहुंचा, कई उड़ानों में हुई देरी, IMD ने जारी किया येलो अलर्ट', 'Delhi Weather Update: शनिवार को दिल्लीवासियों की सुबह घने कोहरे, कम विजिबिलिटी और भीषण ठंड के साथ हुई। भारतीय मौसम विभाग (IMD) ने शीत लहर और घने कोहरे के लिए येलो अलर्ट जारी किया है। 16 जनवरी को लगातार छठे दिन भी शीत लहर का प्रकोप जारी रहा और शहर भर में तापमा…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-5.jpg', 'https://hindi.moneycontrol.com/india/dense-fog-and-cold-wave-lash-delhi-minimum-temperature-drops-to-4-3-degree-celsius-several-flights-delayed-imd-issues-yellow-alert-article-2342286.html', 'Moneycontrol', '2026-01-17 01:58:11', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(44, 1, 'Delhi Pollution: फिर जहरीली हुई दिल्ली की हवा, GRAP-3 की पाबंदियां लागू...जानें क्या होगी पाबंदी', 'दिल्ली-NCR में बढ़ते वायु प्रदूषण को देखते हुए एयर क्वालिटी मैनेजमेंट कमीशन (CAQM) ने ग्रेडेड रिस्पॉन्स एक्शन प्लान (GRAP) के तहत स्टेज-3 की पाबंदियां लागू कर दी हैं। यह कदम इसलिए उठाया गया क्योंकि Delhi-NCR की हवा की हालत और बिगड़ गई थी। एयर क्वालिटी इंडेक्स…', 'https://images.moneycontrol.com/static-hindinews/2025/12/Delhi-AQI-edges-closer-to-severe.jpg', 'https://hindi.moneycontrol.com/india/delhi-pollution-grap-three-restrictions-reimposed-in-delhi-ncr-as-pollution-levels-rise-article-2342188.html', 'Moneycontrol', '2026-01-16 15:13:27', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(45, 1, 'Bahadurgarh Gangrape Case: बस का पीछा कर महिला को घसीटकर ढाबे तक ले गए दरिंदे, फिर किया सामूहिक बलात्कार, चार आरोपी गिरफ्तार', 'Bahadurgarh Gangrape Case: एक 42 साल की महिला के साथ सोमवार को बहादुरगढ़ में एक सुनसान सड़क किनारे ढाबे पर कथित तौर पर सामूहिक दुष्कर्म किया गया। आरोप है कि कुछ लोगों ने उस बस का पीछा किया, जिसमें महिला सफर कर रही थी। इस मामले में पांच आरोपियों में से चार को …', 'https://images.moneycontrol.com/static-hindinews/2026/01/Haryana.jpg', 'https://hindi.moneycontrol.com/india/the-miscreants-chased-the-bus-and-took-the-woman-to-a-dhaba-then-gang-raped-her-four-accused-arrested-article-2341403.html', 'Moneycontrol', '2026-01-16 05:34:43', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(46, 1, 'Train Delays Chandigarh: चंडीगढ़ में घने कोहरे से रेल यातायात बाधित, 2 वंदे भारत और शताब्दी सहित 10 ट्रेनें लेट', 'Train Delays Chandigarh: उत्तर भारत के बड़े हिस्से में छाए घने कोहरे के कारण रेल सेवाएं बाधित रहीं, जिसके कारण गुरुवार को चंडीगढ़ रेलवे स्टेशन पर कई लंबी दूरी और प्रीमियम ट्रेनों के पहुंचने में भारी देरी हुई। कम से कम 10 ट्रेनें निर्धारित समय से देरी से चलीं,…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Chandigarh.jpg', 'https://hindi.moneycontrol.com/india/dense-fog-disrupts-rail-traffic-in-chandigarh-delays-10-trains-including-2-vande-bharat-and-shatabdi-trains-article-2341265.html', 'Moneycontrol', '2026-01-16 04:18:03', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(47, 1, 'Delhi AQI Today: दिल्ली की हवा हुई बेहद खराब, AQI 345 तक पहुंचा, शनिवार तक स्थिति और खराब होने की आशंका', 'Delhi AQI Today: शुक्रवार सुबह दिल्ली की वायु गुणवत्ता में भारी गिरावट आई। केंद्रीय प्रदूषण नियंत्रण बोर्ड (सीपीसीबी) के आंकड़ों के अनुसार, आज सुबह दिल्ली का एयर क्वालिटी इंडेक्स (AQI) 345 दर्ज किया गया है, जो \'बेहद खराब\' श्रेणी में आता है। इससे पहले बृहस्पति…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-4.jpg', 'https://hindi.moneycontrol.com/india/delhi-air-quality-deteriorates-aqi-reaches-345-situation-likely-to-worsen-by-saturday-article-2341180.html', 'Moneycontrol', '2026-01-16 03:13:46', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(48, 1, 'Delhi Cyber Fraud: दिल्ली के रिटायर्ड अफसर को साइबर ठगों ने लगाया चूना, डिजिटल अरेस्ट के नाम पर लूटे ₹2.19 करोड़, 5 आरोपी गिरफ्तार', 'Delhi Cyber Fraud: दिल्ली पुलिस की इंटेलिजेंस फ्यूजन एंड स्ट्रैटेजिक ऑपरेशंस (IFSO) यूनिट ने साइबर धोखाधड़ी के एक मामले में मध्य प्रदेश और उत्तर प्रदेश से पांच लोगों को गिरफ्तार किया है। पुलिस ने बताया कि कंबोडिया में बैठे साइबर अपराधियों ने भारतीय कानून प्रव…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Cyber-fraud-4.jpg', 'https://hindi.moneycontrol.com/india/cyber-%e2%80%8b%e2%80%8bfraudsters-dupe-retired-delhi-officer-looted-rs-2-19-crore-in-the-name-of-digital-arrest-5-accused-arrested-article-2341074.html', 'Moneycontrol', '2026-01-16 02:28:24', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(49, 1, 'Delhi weather: दिल्ली में कड़ाके की ठंड का कहर, तापमान 2.3 डिग्री तक गिरा, IMD ने जारी किया येलो अलर्ट', 'Delhi weather: दिल्ली में शुक्रवार सुबह कड़ाके की ठंड और हल्का कोहरा देखने को मिला। भारत मौसम विज्ञान विभाग (IMD) ने ठंड को लेकर येलो अलर्ट जारी किया हुआ है। 16 जनवरी को लगातार छठे दिन शहर में शीतलहर की स्थिति बनी हुई है और तापमान में भारी गिरावट दर्ज की गई ह…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-weather.jpg', 'https://hindi.moneycontrol.com/india/severe-cold-wreaks-havoc-in-delhi-temperature-drops-to-2-3-degrees-imd-issues-yellow-alert-article-2341028.html', 'Moneycontrol', '2026-01-16 01:49:58', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(50, 1, 'India Open 2026: पहले बंदर के कारण झेलनी पड़ी शर्मिंदगी! अब चिड़िया की बीट से इंडिया ओपन का खेल दो बार रुका! आयोजकों की मुश्किलें बढ़ीं', 'India Open 2026: इंडिया ओपन सुपर 750 में आयोजन संबंधी चिंताओं की लिस्ट हर रोज बढ़ती ही जा रही है। गुरुवार (15 जनवरी) को एचएस प्रणय और सिंगापुर के लोह कीन यू के बीच पुरुष सिंगल्स के दूसरे दौर के मैच के दौरान चिड़िया की बीट के कारण दो बार मैच रोकना पड़ा। इंदिरा…', 'https://images.moneycontrol.com/static-hindinews/2026/01/India-Open-2026-match.jpg', 'https://hindi.moneycontrol.com/india/india-open-2026-match-was-stopped-twice-due-to-bird-droppings-after-facing-embarrassment-the-previous-day-due-to-monkeys-article-2341005.html', 'Moneycontrol', '2026-01-15 17:07:20', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(51, 1, 'दिल्ली एयरपोर्ट पर बड़ा हादसा, एअर इंडिया के विमान की चपेट में आया कार्गो कंटेनर', 'दिल्ली से न्यूयॉर्क जा रहे एयर इंडिया के एयरबस A350 विमान को गुरुवार सुबह ईरान के हवाई क्षेत्र बंद होने के कारण वापस लौटना पड़ा. लैंडिंग के बाद टैक्सीइंग के दौरान विमान के इंजन ने कार्गो कंटेनर को टक्कर मार दी, जिससे इंजन को भारी नुकसान हुआ.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/6968fa3956f17-air-india-engine-damage-153115399-16x9.jpg', 'https://www.aajtak.in/india/news/story/delhi-igi-airport-air-india-plane-hits-cargo-container-delhi-to-new-york-airbus-ntc-ntyv-rpti-2440023-2026-01-15', 'Aajtak.in', '2026-01-15 14:32:50', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(52, 1, 'एयर इंडिया फ्लाइट के इंजन में घुसा बैगेज कंटेनर, दिल्ली एयरपोर्ट पर बड़ा हादसा टला!', 'आज सुबह दिल्ली एयरपोर्ट पर एयर इंडिया के एक विमान के इंजन को नुकसान पहुंचा। यह हादसा तब हुआ जब विमान घने कोहरे में रनवे पर चल रहा था और इंजन में एक बैगेज कंटेनर चला गया। एयर इंडिया ने बताया कि यह विमान एयरबस A350 था। यह घटना उस समय हुई जब विमान दिल्ली एयरपोर्…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Air-India-Flight-Engine.jpg', 'https://hindi.moneycontrol.com/india/air-india-flight-major-accident-was-averted-at-delhi-airport-after-a-baggage-container-in-engine-article-2340911.html', 'Moneycontrol', '2026-01-15 11:15:51', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(53, 1, 'मौसम पर वेस्टर्न डिस्टर्बेंस का असर, गणतंत्र दिवस पर पहाड़ों पर होगी बर्फबारी', 'वेस्टर्न डिस्टर्बेंस के असर से पहाड़ों में मौसम जल्द ही करवट लेने वाला है. ऊंचे इलाकों में लगातार बर्फबारी देखने को मिल सकती है, जबकि निचले क्षेत्रों में बारिश की संभावना रहेगी. बदलते मौसम का असर गणतंत्र दिवस के दिन भी देखा जा सकता है.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/6968bf66b0c4f-himalayan-snowfall-152011685-16x9.jpg', 'https://www.aajtak.in/india/news/story/snowfall-himalayas-weather-western-disturbance-republic-day-26-january-mountain-amlbs-dskc-2439695-2026-01-15', 'Aajtak.in', '2026-01-15 11:06:08', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(54, 1, 'झुलसाने वाली गर्मी से मूसलाधार बारिश तक... 2025 बना धरती का सबसे गर्म साल', 'साल 2025 रिकॉर्ड में दर्ज सबसे गर्म सालों में से एक रहा. बीते साल दुनिया ने चरम मौसम की घटनाओं का सामना किया. कहीं भीषण गर्मी, कहीं भारी बारिश जैसे हालात रहे. लगातार बढ़ते तापमान ने यह साफ कर दिया है कि ग्लोबल वॉर्मिंग के नकारात्मक असर अब सीधे तौर पर दिखाई दे…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/696898dc87faa-global-warming-impacts-153550541-16x9.jpg', 'https://www.aajtak.in/science/story/global-warming-2025-extreme-weather-heatwaves-floods-record-hottest-year-amlbs-rptc-2439111-2026-01-15', 'Aajtak.in', '2026-01-15 07:48:40', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(55, 1, 'Delhi AQI: दिल्ली में जहरीली हवा के साथ पड़ रही कड़ाके की ठंड, चांदनी चौक में AQI 400 के पार', 'Delhi AQI Today: दिल्ली में कड़ाके की ठंड और घने कोहरे के बीच प्रदूषण का स्तर लगातार खतरनाक बना हुआ है। आज सुबह 6:05 बजे दिल्ली का औसत वायु गुणवत्ता सूचकांक (AQI) 356 दर्ज किया गया, जो \'बहुत खराब\' श्रेणी में आता है। सेंट्रल पॉल्यूशन कंट्रोल बोर्ड (CPCB) के अन…', 'https://images.moneycontrol.com/static-hindinews/2025/12/Delhi-AQI-edges-closer-to-severe.jpg', 'https://hindi.moneycontrol.com/india/delhi-pollution-update-city-s-air-quality-remains-very-poor-chandni-chowk-worst-at-404-article-2340723.html', 'Moneycontrol', '2026-01-15 03:24:45', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(56, 1, 'Delhi Weather Today: दिल्ली में कोहरे और कड़ाके की ठंड का कहर, IMD ने येलो और रेड अलर्ट किया जारी', 'Delhi Weather Today: भारतीय मौसम विभाग (IMD) ने सुबह 9:03 बजे तक \"घने कोहरे\" की चेतावनी जारी की है। वहीं, बुधवार को लोधी रोड पर न्यूनतम तापमान 3.6 डिग्री सेल्सियस तक गिरने के साथ ही राष्ट्रीय राजधानी में कड़ाके की ठंड पड़ रही है। गुरुग्राम में भी पारा 3.5 डिग…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-3.jpg', 'https://hindi.moneycontrol.com/india/fog-and-severe-cold-wreak-havoc-in-delhi-imd-issues-yellow-and-red-alert-article-2340662.html', 'Moneycontrol', '2026-01-15 02:10:44', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(57, 1, 'आख‍िरी गेंद पर निकला WPL में नतीजा, दिल्ली ने UP को धोया... शेफाली-ल‍िजेल चमकी', 'WPL 2026 में  दिल्ली कैपिटल्स ने बुधवार को यूपी वॉरियर्स को आख‍िरी गेंद पर रोमांचक अंदाज में हराया और सीजन की पहली जीत दर्ज की. दिल्ली की जीत में लिजेल ली ने चमक बिखेरी. शेफाली वर्मा प्लेयर ऑफ द मैच रहीं.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/6967d6fe54e5b-shafali-verma-and-lizelle-lee-144840914-16x9.jpg', 'https://www.aajtak.in/sports/cricket/story/wpl-2026-dcw-vs-upw-match-highlights-shafali-verma-lizelle-lee-tspok-dskc-2439188-2026-01-14', 'Aajtak.in', '2026-01-14 17:50:58', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(58, 1, 'Tej Pratap Yadav: \'RJD का JJD में विलय होगा...\'; पिता लालू प्रसाद से मुलाकात के बाद तेज प्रताप यादव का बड़ा दावा', 'Tej Pratap Yadav News: राष्ट्रीय जनता दल (RJD) के अध्यक्ष लालू प्रसाद बुधवार (14 जनवरी) को अपने बड़े बेटे और जन शक्ति जनता दल (JJD) प्रमुख तेज प्रताप यादव के आवास पर आयोजित मकर संक्रांति के भोज में शामिल हुए। हालांकि, इससे कुछ महीने पहले ही उन्होंने तेज प्रता…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Lalu-attends-Tej-Pratap.jpg', 'https://hindi.moneycontrol.com/india/tej-pratap-yadav-rjd-will-merge-with-the-jjd-tej-pratap-makes-a-big-claim-after-meeting-his-father-lalu-prasad-article-2340546.html', 'Moneycontrol', '2026-01-14 14:42:14', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(59, 1, 'Delhi Pollution: \'दिल्ली बैडमिंटन के लिए ठीक नहीं...\'; प्रदूषण के कारण \'इंडिया ओपन\' के लिए भारत नहीं आए शटलर एंटोनसन, लगा भारी जुर्माना', 'Anders Antonsen Withdraws India Open 2026: दुनिया के तीसरे नंबर के खिलाड़ी डेनमार्क के एंडर्स एंटोनसन ने बुधवार (14 जनवरी) को कहा कि दिल्ली में बहुत अधिक प्रदूषण के कारण उन्होंने लगातार तीसरे साल \'इंडिया ओपन सुपर 750 बैडमिंटन टूर्नामेंट\' में हिस्सा नहीं लेने …', 'https://images.moneycontrol.com/static-hindinews/2026/01/Anders-Antonsen.jpg', 'https://hindi.moneycontrol.com/sports/anders-antonsen-withdraws-india-open-2026-on-delhi-pollution-denmark-shuttler-calls-unsuitable-for-badminton-article-2340487.html', 'Moneycontrol', '2026-01-14 13:29:27', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(60, 1, 'PM मोदी ने केंद्रीय मंत्री मुरुगन के घर पोंगल समारोह में लिया हिस्सा, बोले- ये मेरे लिए सौभाग्य की बात', 'प्रधानमंत्री नरेंद्र मोदी ने आज दिल्ली में केंद्रीय मंत्री एल मुरुगन के आवास पर पोंगल समारोह में हिस्सा लिया है. उन्होंने यहां गौसेवा भी की. इससे पहले पीएम ने मकर संक्रांति, भोगाली बिहू और पोंगल के अवसर पर देशवासियों को शुभकामनाएं दीं और पोंगल को तमिल परंपराओ…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/69672741de227-pm-modi-141851561-16x9.jpg', 'https://www.aajtak.in/india/delhi/story/pm-modi-pongal-celebration-l-murugan-residence-sankranti-bhogali-bihu-ntc-udny-dskc-2438481-2026-01-14', 'Aajtak.in', '2026-01-14 05:19:57', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(61, 1, 'दिल्ली में ठंड, कोहरे और प्रदूषण की ट्रिपल मार... जानें मौसम का हाल', 'Delhi Cold Wave Live Updates: दिल्ली समेत भारत के कई राज्यों में ठंड का प्रकोप लगातार बढ़ता जा रहा है. शीतलहर के बीच राजधानी की हवा और ज्यादा जहरीली हो गई है. आज सुबह दिल्ली का ओवरऑल एयर क्वालिटी इंडेक्स (AQI) 357 दर्ज किया गया है. मौसम विभाग के अनुसार आज दिल…', 'https://akm-img-a-in.tosshub.com/aajtak/images/breaking_news/202601/69671b496d6fc-delhi-ncr-weather-142747586-16x9.jpg', 'https://www.aajtak.in/india/news/story/delhi-ncr-weather-live-updates-india-cold-wave-poor-air-quality-fog-imd-alert-amlbs-2438447-2026-01-14', 'Aajtak.in', '2026-01-14 04:28:44', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(62, 1, 'Delhi Motorcycle Accident: कुत्तों के पीछा करने से तेज रफ्तार बाइक खाई में गिरी, एक युवक की मौत, एक घायल', 'Delhi Motorcycle Accident: दक्षिण-पूर्वी दिल्ली के जैतपुर पुस्ता इलाके में एक मोटरसाइकिल के खाई में गिरने से 20 वर्षीय युवक की मौत हो गई और 29 वर्षीय युवक घायल हो गया। बताया जा रहा है कि कुत्तों द्वारा पीछा किए जाने के दौरान यह घटना हुई। पुलिस के अनुसार, मृतक…', 'https://images.moneycontrol.com/static-hindinews/2026/01/delhi-accident-1.jpg', 'https://hindi.moneycontrol.com/india/road-accident-in-delhi-a-speeding-bike-chased-by-dogs-falls-into-a-ditch-one-youth-killed-one-injured-article-2339532.html', 'Moneycontrol', '2026-01-14 03:49:16', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(63, 1, 'Delhi AQI: दिल्ली-NCR में कड़ाके की ठंड और जहरीली हवा का कहर, 3°C तक गिरा पारा; AQI 600 के पार', 'Delhi AQI Today: दिल्ली-एनसीआर में मौसम के दोहरे तेवर देखने को मिल रहे है। दिन में चटक धूप राहत दे रही है, तो रात होते ही शीतलहर और घने कोहरे ने जनजीवन अस्त-व्यस्त कर दिया है। भारतीय मौसम विज्ञान विभाग (IMD) ने स्थिति को देखते हुए ऑरेंज अलर्ट जारी किया है। सा…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-AQI-404-Struggles-with-Poor-Visibility.jpg', 'https://hindi.moneycontrol.com/india/delhi-ncr-aqi-today-14-january-cold-wave-dense-fog-low-visibility-air-quality-severe-level-imd-orange-alert-article-2339377.html', 'Moneycontrol', '2026-01-14 02:42:45', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(64, 1, '\'शक्सगाम वैली पर चीन का दावा अवैध है…\', MEA के बाद आर्मी चीफ का दो टूक जवाब', 'थलसेना प्रमुख जनरल उपेंद्र द्विवेदी ने कहा कि इस क्षेत्र में किसी भी प्रकार की गतिविधि को भारत स्वीकार नहीं करेगा. विदेश मंत्रालय ने भी पहले ही इस मुद्दे पर अपना आधिकारिक रुख स्पष्ट कर दिया है. ये बयान भारत की क्षेत्रीय संप्रभुता और सुरक्षा के प्रति उसकी प्रत…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/6966538a302fc-army-chief-general-upendra-dwivedi-addresses-a-press-conference-in-delhi-on-tuesday-132001216-16x9.jpg', 'https://www.aajtak.in/india/news/story/india-declares-china-pakistan-shaksgam-valley-agreement-illegal-army-chief-ntcpmm-dskc-2438213-2026-01-13', 'Aajtak.in', '2026-01-13 14:23:18', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(65, 1, 'आमिर ने जिस फिल्म के लिए पहली बार गाली-गलौज की, अब उसका सीक्वल बनेगा!', 'आमिर ने जिस फिल्म के लिए पहली बार गाली-गलौज की, अब उसका सीक्वल बनेगा!thelallantop.com', 'https://static.thelallantop.com/images/post/202601/1768286909884_delhi_belly_2_(1).webp', 'https://www.thelallantop.com/entertainment/post/delhi-belli-2-the-film-that-made-aamir-khan-swear-for-the-first-time-is-finally-getting-a-sequel', 'Thelallantop.com', '2026-01-13 10:48:56', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(66, 1, 'BRICS 2026: BRICS इंडिया 2026 का लोगो और वेबसाइट लॉन्च, विदेश मंत्री एस जयशंकर ने बताईं वैश्विक प्राथमिकताएं', 'BRICS 2026: भारत ने मंगलवार को BRICS 2026 की अध्यक्षता के लिए अपना लोगो और आधिकारिक वेबसाइट औपचारिक रूप से लॉन्च कर दिया है। यह लॉन्च नई दिल्ली में हुआ, जिसमें विदेश मंत्री एस जयशंकर शामिल हुए और आगामी वर्ष के लिए भारत की प्राथमिकताओं के बारे में बताया।लोगो भ…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Brics-2026-2.jpg', 'https://hindi.moneycontrol.com/india/brics-india-2026-logo-and-website-launched-external-affairs-minister-s-jaishankar-outlines-global-priorities-article-2338736.html', 'Moneycontrol', '2026-01-13 08:40:20', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(67, 1, 'पाकिस्तान के अंदर ग्राउंड एक्शन को तैयार थी सेना, आर्मी चीफ ने ऑपरेशन सिंदूर पर किया वॉर प्लान का खुलासा', 'ऑपरेशन सिंदूर के तनाव के क्षणों को याद करते हुए आर्मी चीफ जनरल उपेन्द्र द्विवेदी ने कहा है कि ऑपरेशन सिंदूर के दौरान इंडियन आर्मी ग्राउंड एक्शन के लिए तैयार थी. अगर पाकिस्तान थोड़ी सी भी गलत करता तो भारत ने जमीनी एक्शन का प्लान बना रखा था.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/6965fb365bff3-indian-army-in-jammu-135840952-16x9.jpeg', 'https://www.aajtak.in/defence-news/story/india-ground-action-operation-sindoor-army-chief-general-upendra-dwivedi-ntcppl-dskc-2437810-2026-01-13', 'Aajtak.in', '2026-01-13 08:18:41', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(68, 1, 'Delhi Coldest Morning: दिल्ली में इस सीजन की सबसे ठंडी सुबह, तापमान गिरकर पहुंचा 3°C, पंजाब और हरियाणा में रेड अलर्ट', 'Delhi Coldest Morning: मंगलवार को दिल्ली में मौसम की सबसे ठंडी सुबह रही, जब पारा गिरकर 3 डिग्री सेल्सियस तक पहुंच गया। वहीं, उत्तर भारत के कई हिस्सों में भी तापमान शून्य के करीब पहुंच गया, जिसके चलते मौसम एजेंसियों ने पंजाब और हरियाणा के लिए उच्चतम स्तर की चे…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-2.jpg', 'https://hindi.moneycontrol.com/india/delhi-records-season-coldest-morning-as-temperature-drops-to-3-degrees-celcius-punjab-and-haryana-on-red-alert-article-2338314.html', 'Moneycontrol', '2026-01-13 04:22:10', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(69, 1, 'शिमला से ठंडी हुई राजधानी दिल्ली, कड़ाके की ठंड और प्रदूषण ने बढ़ाई मुश्किल; IMD ने जारी किया \'ऑरेंज अलर्ट\'', 'Delhi AQI Today: राष्ट्रीय राजधानी दिल्ली इस समय भीषण शीत लहर और घने कोहरे की चपेट में है। आज सुबह दिल्ली का न्यूनतम तापमान गिरकर 3.2°C दर्ज किया गया, जो पिछले तीन वर्षों में जनवरी की सबसे ठंडी सुबह है। मौसम विभाग (IMD) ने शहर में \'ऑरेंज अलर्ट\' जारी किया है औ…', 'https://images.moneycontrol.com/static-hindinews/2025/11/Delhi-AQI-Today-severe-.jpg', 'https://hindi.moneycontrol.com/india/delhi-air-quality-today-temperature-dips-dense-fog-cold-wave-and-very-poor-aqi-grip-city-check-aqi-in-your-area-article-2338047.html', 'Moneycontrol', '2026-01-13 02:02:05', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(70, 1, 'Yamuna River Cruise: अब दिल्ली यमुना पर लग्जरी क्रूज का ले सकेंगे गोवा वाला आनंद! NCR वालों को जल्द मिलेगा तोहफा, जानें- सबकुछ', 'Delhi Yamuna River Cruise: दिल्ली वाले जल्द ही यमुना नदी पर इंटरनेशनल स्टैंडर्ड के लग्जरी क्रूज का आनंद ले पाएंगे। क्रूज सेवा शुरू करने की तैयारियां लगभग पूरी होने के करीब है। दिल्ली सरकार अपनी रिवरफ्रंट टूरिज्म और रिक्रिएशन प्लान के तहत 40 सीटों वाला क्रूज ल…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Yamuna-River-Cruise.jpg', 'https://hindi.moneycontrol.com/india/yamuna-river-cruise-delhiites-to-get-40-seater-luxury-cruise-from-this-date-check-details-here-article-2337996.html', 'Moneycontrol', '2026-01-12 16:27:33', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(71, 1, '15 जनवरी के बाद बदलेगा मौसम, दिल्ली से राजस्थान तक पाले का अलर्ट!', 'Weather Forecast: मौसम विभाग के पूर्वानुमान के मुताबिक, 15 जनवरी से एक नए पश्चिमी विक्षोभ यानी वेस्टर्न डिस्टर्बेंस के पश्चिमी हिमालयी क्षेत्र की ओर बढ़ने की संभावना है. जिसके असर से मौसम बदलेगा और राजस्थान, दिल्ली, पंजाब, हरियाणा समेत उत्तर भारत के कई राज्यो…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/6964cff2a764f-cold-wave-122710142-16x9.png', 'https://www.aajtak.in/india/news/story/imd-issued-red-alert-for-punjab-haryana-rajasthan-cold-wave-dense-fog-india-weather-forecast-mausam-news-szlbs-dskc-2437144-2026-01-12', 'Aajtak.in', '2026-01-12 10:42:35', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(72, 1, 'Delhi AQI: दिल्ली में \'कोल्ड वेव\' और \'जहरीली हवा\' का डबल अटैक, AQI 300 के पार; IMD ने जारी किया घने कोहरे का येलो अलर्ट', 'Delhi AQI Today: दिल्ली-NCR समेत पूरा उत्तर भारत इस समय ठंड और प्रदूषण की दोहरी मार झेल रहा है। एक तरफ कड़ाके की ठंड और शीतलहर ने लोगों को घरों में कैद कर दिया है, तो दूसरी तरफ हवा की गुणवत्ता लगातार \'खराब\' और \'बहुत खराब\' श्रेणी के बीच झूल रही है। आज सुबह दिल…', 'https://images.moneycontrol.com/static-hindinews/2025/11/Delhi-AQI-letest-update.jpg', 'https://hindi.moneycontrol.com/india/delhi-air-quality-very-poor-category-aqi-300-imd-issue-yellow-alert-for-cold-wave-article-2336754.html', 'Moneycontrol', '2026-01-12 02:39:18', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(73, 1, 'Rajasthan Cold Wave: राजस्थान में शीत लहर का कहर, कई जिलों में बंद रहेंगे स्कूल, टाइमिंग में भी किया गया बदलाव', 'Rajasthan Cold Wave: राजस्थान के कुछ हिस्सों में तापमान शून्य से नीचे गिरने और राज्य भर में शीत लहर के तेज होने के कारण, जिला प्रशासन ने आगामी दिनों के लिए स्कूलों को बंद रखने और समय में बदलाव की घोषणा की है। जयपुर में, जिला प्रशासन ने रविवार को सरकारी और निज…', 'https://images.moneycontrol.com/static-hindinews/2026/01/राजस्थान-1-1.jpg', 'https://hindi.moneycontrol.com/india/cold-wave-wreaks-havoc-in-rajasthan-schools-to-remain-closed-in-many-districts-timings-also-changed-article-2336719.html', 'Moneycontrol', '2026-01-12 02:21:40', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(74, 1, 'Delhi: अमेरिका से लौटे डॉक्टर कपल से 15 करोड़ की ठगी, 17 दिनों तक डिजिटल अरेस्ट में रखा', '<!--StartFragment -->दिल्ली में रहने वाले एक बुजुर्ग एनआरआई डॉक्टर दंपती के साथ बड़ी साइबर ठगी का मामला सामने आया है। साइबर ठगों ने उन्हें करीब दो हफ्ते से ज़्यादा समय तक डिजिटल अरेस्ट में रखा। इस दौरान ठगों ने उनसे कुल 14.85 करोड़ रुपये ठग लिए। पीड़ित दंपती …', 'https://images.moneycontrol.com/static-hindinews/2025/03/digital-arrest.jpg', 'https://hindi.moneycontrol.com/india/nri-couple-in-delhi-duped-of-nearly-15-crore-digitally-arrested-for-two-weeks-article-2336622.html', 'Moneycontrol', '2026-01-11 10:21:11', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(75, 1, 'Delhi: RWA प्रेसिडेंट के सिर में गोली मारकर हत्या, पति की हत्या में चश्मदीद गवाह थी महिला', '<!--StartFragment -->राजधानी दिल्ली में एक ऐसी वारदात घटी है, जिसने शहर के कानून व्यवस्था पर भी सवाल खड़े कर दिए हैं। शनिवार को उत्तर-पश्चिम दिल्ली के शालीमार बाग इलाके में एक 44 वर्षीय महिला की बेहद नजदीक से सिर में गोली मारकर हत्या कर दी गई। पुलिस अधिकारियो…', 'https://images.moneycontrol.com/static-hindinews/2025/12/murder-news-photo.jpg', 'https://hindi.moneycontrol.com/india/delhi-resident-welfare-association-president-shot-dead-key-witness-in-husband-murder-case-article-2336599.html', 'Moneycontrol', '2026-01-11 08:58:53', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(76, 1, 'दिल्ली में शीतलहर का असर जारी, तापमान में गिरावट', 'Delhi Pollution Live Updates: दिल्ली समेत भारत के कई हिस्सों में ठंड का कहर जारी है. दिल्ली में कल अब तक की सबसे ठंडी सुबह दर्ज की गई है. आज भी तापमान में कमी महसूस की जा रही है. कई इलाकों में शीतलहर का असर जारी है.', 'https://akm-img-a-in.tosshub.com/aajtak/images/breaking_news/202601/69632908de7e0-delhi-ncr-weather-live-113723254-16x9.jpg', 'https://www.aajtak.in/india/news/story/delhi-ncr-weather-live-updates-india-cold-wave-poor-air-quality-fog-amlbs-2436119-2026-01-11', 'Aajtak.in', '2026-01-11 04:38:26', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(77, 1, 'Delhi AQI: दिल्ली में जहरीली हवा का कहर जारी, गणतंत्र दिवस से पहले \'गैस चैंबर\' बनी राजधानी, गंभीर श्रेणी में AQI', 'Delhi AQI Today: आज सुबह दिल्ली एक बार फिर जहरीले स्मॉग की गिरफ्त में है। गणतंत्र दिवस की तैयारियों के बीच, राजधानी की हवा लगातार तीसरे दिन \'बहुत खराब\' श्रेणी में बनी हुई है। मौसम की सुस्ती और गिरते तापमान ने प्रदूषक तत्वों को जमीन के करीब कैद कर दिया है, जिस…', 'https://images.moneycontrol.com/static-hindinews/2025/12/Delhi-AQI-edges-closer-to-severe.jpg', 'https://hindi.moneycontrol.com/india/delhi-ncr-aqi-alert-today-11-january-2026-pollution-air-quality-today-slips-to-very-poor-dense-fog-article-2336517.html', 'Moneycontrol', '2026-01-11 02:00:25', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(78, 1, 'दिल्ली में ठंड और कोहरे का कहर, उड़ानों की थमी रफ्तार... जानें मौसम का हाल', 'Delhi Weather Live Updates: दिल्ली में ठंड का असर तेज हो गया है. तापमान में लगातार गिरावट महसूस की जा रही है. वहीं, दिल्ली समेत भारत के कई हिस्सों में घने कोहरे के कारण लोगों को परेशानी का सामना करना पड़ रहा है. ट्रेन से लेकर फ्लाइट्स तक देरी से चल रही हैं.', 'https://akm-img-a-in.tosshub.com/aajtak/images/breaking_news/202601/6961de0587efd-delhi-ncr-weather-live-100503487-16x9.jpg', 'https://www.aajtak.in/india/news/story/delhi-ncr-weather-live-updates-imd-forecast-india-cold-wave-dense-fog-alert-amlbs-2435311-2026-01-10', 'Aajtak.in', '2026-01-10 05:11:14', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(79, 1, 'IMD Alert: चेन्नई और तमिलनाडु के अन्य हिस्सों में भारी बारिश की संभावना, IMD ने जारी किया ऑरेंज अलर्ट', 'IMD Alert: भारतीय मौसम विज्ञान विभाग (IMD) ने अपने मौसम बुलेटिन में दक्षिण-पश्चिम बंगाल की खाड़ी में गहरे दबाव की चेतावनी जारी की है। मौसम एजेंसी ने तमिलनाडु के तिरुवरूर, नागपट्टिनम, मयिलादुथुराई और कुड्डालोर जिलों, पुडुचेरी और कराईकल क्षेत्र में शनिवार को भा…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Tamilnadu.jpg', 'https://hindi.moneycontrol.com/india/heavy-rain-likely-in-chennai-and-other-parts-of-tamil-nadu-imd-issues-orange-alert-article-2336210.html', 'Moneycontrol', '2026-01-10 03:48:40', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(80, 1, 'Delhi AQI: दिल्ली में सांस लेना मुश्किल, AQI पहुंचा 358, ठंड और प्रदूषण से हालात बदतर', 'Delhi AQI: केंद्रीय प्रदूषण नियंत्रण बोर्ड (CPCB) के समीर ऐप के आंकड़ों के अनुसार, शनिवार सुबह 6:05 बजे एयर क्वालिटी इंडेक्स (AQI) 358 दर्ज किया गया, जिससे दिल्ली की वायु गुणवत्ता \'बहुत खराब\' श्रेणी में बनी रही। वहीं, शुक्रवार की सुबह, AQI 318 दर्ज किया गया, …', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-AQI-1.jpg', 'https://hindi.moneycontrol.com/india/breathing-difficult-in-delhi-aqi-reaches-358-cold-and-pollution-worsen-the-situation-article-2336197.html', 'Moneycontrol', '2026-01-10 02:31:03', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(81, 1, '\'दोनों NCP के कार्यकर्ता एकजुट होना चाहते हैं\'; ठाकरे ब्रदर्स के बाद क्या अब चाचा-भतीजा आएंगे साथ? अजित पवार का बड़ा बयान', 'Maharashtra Politics: महाराष्ट्र की सियासत में हर रोज एक नया उलेटफेर देखने को मिल रहा है। ठाकरे ब्रदर्स के बाद के बाद अब महाराष्ट्र के उपमुख्यमंत्री अजित पवार और उनके चाचा शरद पवार गुट के बीच गठबंधन की बात चल रही है। राष्ट्रवादी कांग्रेस पार्टी (NCP) के प्रमु…', 'https://images.moneycontrol.com/static-hindinews/2026/01/ajit-pawar-sharad-pawar_.jpg', 'https://hindi.moneycontrol.com/india/maharashtra-politics-ncp-factions-want-to-unite-uncle-and-nephew-now-come-together-ajit-pawar-big-statement-amid-bmc-polls-article-2335926.html', 'Moneycontrol', '2026-01-09 11:41:48', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(82, 1, 'Delhi Suicide: \'काम के दबाव ने मुझे तोड़ दिया...\'; साकेत कोर्ट के कर्मचारी ने बिल्डिंग से कूदकर दी जान, सुसाइड नोट में वर्क प्रेशर का जिक्र', 'Delhi Suicide News: दिल्ली पुलिस ने शुक्रवार (9 जनवरी) को बताया कि राष्ट्रीय राजधानी में साकेत डिस्ट्रिक्ट कोर्ट कॉम्प्लेक्स के अंदर कथित तौर पर काम के दबाव से परेशान एक पुरुष कर्मचारी ने बिल्डिंग से कूदकर आत्महत्या कर ली। पुलिस ने बताया कि मृतक के पास से एक …', 'https://images.moneycontrol.com/static-hindinews/2026/01/Saket-court-employee.jpg', 'https://hindi.moneycontrol.com/india/delhi-suicide-case-work-pressure-broke-me-saket-court-employee-jumps-to-his-death-from-building-mentions-work-pressure-article-2335726.html', 'Moneycontrol', '2026-01-09 10:31:07', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(83, 1, 'I-PAC Raids Row: बंगाल के बाद अब दिल्ली में खेला! गृह मंत्रालय के बाहर TMC का प्रदर्शन, पुलिस ने 8 सांसदों को हिरासत में लिया', 'I-PAC Raids Row: पश्चिम बंगाल में सत्ताधारी तृणमूल कांग्रेस (TMC) के सांसद डेरेक ओ ब्रायन और महुआ मोइत्रा की अगुवाई में सांसदों ने दिल्ली में गृह मंत्रालय के कार्यालय के बाहर विरोध प्रदर्शन किया। इस दौरान दिल्ली पुलिस ने सभी को हिरासत में ले लिया। TMC सांसदों…', 'https://images.moneycontrol.com/static-hindinews/2026/01/TMC_MPs.jpg', 'https://hindi.moneycontrol.com/india/ipac-raids-row-mamata-banerjee-tmc-stages-massive-protest-outside-amit-shah-office-delhi-police-detain-8-mp-article-2335326.html', 'Moneycontrol', '2026-01-09 06:08:58', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(84, 1, 'Delhi Water Supply Disruption: पानी के लिए तरसेंगे दिल्ली के लोग, इन इलाकों में दो दिन तक बाधित रहेगी जल आपूर्ति, DJB ने जारी की चेतावनी', 'Delhi Water Supply Disruption: दिल्ली जल बोर्ड ने राष्ट्रीय राजधानी के निवासियों को दो दिन की जल आपूर्ति बाधित होने की चेतावनी देते हुए एक परामर्श जारी किया है। दिल्ली जल बोर्ड ने बताया कि हिंदू राव रिजर्वॉयर से जुड़े इलाकों में 9 और 10 जनवरी को पानी की कमी ह…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-waterh.jpg', 'https://hindi.moneycontrol.com/india/delhi-residents-will-struggle-for-water-supply-disrupted-for-two-days-in-these-areas-djb-issues-warning-article-2335255.html', 'Moneycontrol', '2026-01-09 06:00:46', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(85, 1, 'Cold wave in Delhi: दिल्ली में पारा 4.6 डिग्री तक लुढ़का, NCR में अचानक हुई बारिश ने बढ़ाई ठंड; जानिए मौसम का हाल', 'Cold wave in Delhi: इंडिया मेट्रोलॉजिकल डिपार्टमेंट (IMD) के मुताबिक, शुक्रवार (9 जनवरी) को राष्ट्रीय राजधानी दिल्ली में इस मौसम का सबसे कम तापमान दर्ज किया गया। IMD के मुताबिक, शुक्रवार सुबह तापमान सामान्य से 2.3 डिग्री कम 4.6 डिग्री सेल्सियस दर्ज किया गया। …', 'https://images.moneycontrol.com/static-hindinews/2025/01/Winter-Cold-Wave-AI.jpg', 'https://hindi.moneycontrol.com/india/delhi-temperature-drops-amid-cold-wave-surprise-rain-in-ncr-imd-issues-alert-weather-update-article-2335196.html', 'Moneycontrol', '2026-01-09 04:40:22', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(86, 1, 'Iran Protest: ईरान के 50 शहरों में भारी विरोध-प्रदर्शन! सड़कों पर दिखा लोगों का हुजूम, इंटरनेट ब्लैकआउट, टेलीफोन सेवाएं भी ठप, 45 की मौत', 'Iran Protest: ईरान के निर्वासित क्राउन प्रिंस रजा पहलवी की अपील पर तेहरान और देश के अन्य हिस्सों में प्रदर्शनकारियों के विरोध प्रदर्शन में शामिल होने के बाद गुरुवार (8 जनवरी) रात को इंटरनेट और टेलीफोन लाइन काट दी गई। खस्ताहाल अर्थव्यवस्था को लेकर ईरान में विर…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Iran-Protest_.jpg', 'https://hindi.moneycontrol.com/world/iran-protests-internet-shutdown-digital-blackout-unrest-in-tehran-khamenei-45-death-raza-pahlavi-heads-to-trump-article-2334904.html', 'Moneycontrol', '2026-01-09 02:03:12', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(87, 1, 'Delhi AQI Today: दिल्ली की हवा हुई और जहरीली, AQI 318 के पार, 24 इलाकों में हालात बेहद खराब', 'Delhi AQI Today: शुक्रवार सुबह दिल्ली की वायु गुणवत्ता \'बहुत खराब\' श्रेणी में बनी रही। केंद्रीय प्रदूषण नियंत्रण बोर्ड (CPCB) के समीर ऐप से प्राप्त आंकड़ों के अनुसार, सुबह 6:05 बजे एयर क्वालिटी इंडेक्स (AQI) 318 दर्ज किया गया। राष्ट्रीय राजधानी में एक दिन पहल…', 'https://images.moneycontrol.com/static-hindinews/2026/01/AQI-1.jpg', 'https://hindi.moneycontrol.com/india/delhi-air-becomes-more-toxic-aqi-crosses-318-conditions-very-bad-in-24-areas-article-2334906.html', 'Moneycontrol', '2026-01-09 02:02:05', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(88, 1, 'Meesho के शेयर में दनादन लोअर सर्किट, CXO ने छोड़ी कंपनी, 2Cr थी सैलरी', 'Meesho Share में बीते दो दिनों से तगड़ी गिरावट देखने को मिल रही है. गुरुवार को भी इस ई-कॉमर्स स्टॉक में Lower Circuit लगा नजर आया. इसी बीच कंपनी में एक बड़े इस्तीफे की खबर आई है.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/695f9b0f6d9c7-meesho-share-lower-circuit-085449868-16x9.jpg', 'https://www.aajtak.in/business/news/story/meesho-share-lower-circuit-now-big-resign-megha-agarwal-salary-more-than-2-crore-tutc-dskc-2434001-2026-01-09', 'Aajtak.in', '2026-01-09 01:02:01', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(89, 1, 'Delhi Violence: तुर्कमान गेट हिंसा मामले में 11 गिरफ्तार! 10 इन्फ्लुएंसर और WhatsApp ग्रुप जांच के दायरे में, सपा नेता को नोटिस भेजने की तैयारी', 'Turkman Gate violence:  दिल्ली पुलिस ने तुर्कमान गेट हिंसा के सिलसिले में छह और गिरफ्तारियां की है। फैज-ए-इलाही मस्जिद के पास अवैध कब्जे वाले क्षेत्र को ध्वस्त करने के बारे में झूठे दावे करने वाले कम से कम 10 सोशल मीडिया इन्फ्लुएंसरों की पहचान हुई है। इन नई ग…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Turkman-Gate-violence.jpg', 'https://hindi.moneycontrol.com/india/delhi-violence-11-arrested-in-turkman-gate-case-10-influencers-whatsapp-groups-sp-leader-under-investigation-article-2334887.html', 'Moneycontrol', '2026-01-08 17:41:34', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(90, 1, 'I-PAC Raids Row: \'प्रतीक जैन के घर से अहम सबूत अपने साथ ले गईं ममता बनर्जी\'; बंगाल सीएम पर ED का बड़ा आरोप', 'I-PAC Raids Row: प्रवर्तन निदेशालय (ED) ने गुरुवार (8 जनवरी) को आरोप लगाया कि कथित कोयला तस्करी से जुड़े मनी लॉन्ड्रिंग मामले में पॉलिटिकल कंसल्टिंग फर्म I-PAC के डायरेक्टर प्रतीक जैन के कोलकाता स्थित आवास में उसकी छापेमारी के दौरान पश्चिम बंगाल की मुख्यमंत्र…', 'https://images.moneycontrol.com/static-hindinews/2026/01/edvstmc.jpg', 'https://hindi.moneycontrol.com/india/ipac-raids-row-mamata-banerjee-took-important-evidence-from-prateek-jain-kolkata-house-ed-allegation-bengal-cm-article-2334684.html', 'Moneycontrol', '2026-01-08 12:22:01', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(91, 1, 'Delhi Road Accident: सिरी फोर्ट के पास भीषण सड़क हादसा, तेज रफ्तार कार की टक्कर में टैक्सी चालक और यात्री की मौत, एक घायल', 'Delhi Road Accident: बुधवार तड़के दक्षिण दिल्ली के सिरी फोर्ट के पास एक कार की टक्कर में एक टैक्सी चालक और एक यात्री की मौत हो गई और एक अन्य व्यक्ति गंभीर रूप से घायल हो गया। मृतकों की पहचान गिरजा लाल भारद्वाज (43) और रणजीत (30) के रूप में हुई है। सुबह करीब 4…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-Accident.jpg', 'https://hindi.moneycontrol.com/india/taxi-driver-and-passenger-killed-one-injured-in-collision-with-speeding-car-near-siri-fort-in-delhi-article-2333846.html', 'Moneycontrol', '2026-01-08 05:52:40', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(92, 1, 'फैज-ए-इलाही मस्जिद का पूरा केस, बुलडोजर एक्शन... तुर्कमान गेट मामले की परत दर परत कहानी', 'दिल्ली के तुर्कमान गेट इलाके में हुई हिंसा के बाद कड़ी सुरक्षा व्यवस्था लागू कर दी गई है. कोर्ट के आदेश पर अतिक्रमण हटाने के दौरान पत्थरबाजी हुई थी. अब इस मामले में पुलिस ने 30 पत्थरबाजों की पहचान कर ली है. फिलहाल इलाका शांत है.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/695f3be260adb-turkman-gate-violence-080844645-16x9.png', 'https://www.aajtak.in/india/delhi/story/turkman-gate-violence-court-order-encroachment-drive-police-action-full-story-ntc-agkp-dskc-2433329-2026-01-08', 'Aajtak.in', '2026-01-08 05:24:57', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(93, 1, 'दिल्ली: मस्जिद के पास बवाल पर एक्शन तेज... 30 पत्थरबाजों की हुई पहचान, खंगाले गए 450 से ज्यादा वीडियो', 'दिल्ली के तुर्कमान गेट में अतिक्रमण हटाने के दौरान हुई हिंसा में दिल्ली पुलिस ने करीब 30 पत्थरबाजों की पहचान की है. हिंसा के साढ़े चार सौ से अधिक वीडियो मिले हैं, जिनका विश्लेषण किया जा रहा है.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/695f34e4b8983-turkman-gate-violence-083855902-16x9.png', 'https://www.aajtak.in/india/delhi/story/turkman-gate-violence-delhi-police-stone-pelters-identified-video-evidence-investigation-ntc-agkp-rpti-2433305-2026-01-08', 'Aajtak.in', '2026-01-08 04:29:11', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(94, 1, 'दिल्ली दंगा केस: गुलफिशा फातिमा सहित 4 आरोपी जेल से छूटे, भावुक लम्हे का वीडियो वायरल', 'साल 2020 के उत्तर-पूर्वी दिल्ली दंगों की साजिश के मामले में सुप्रीम कोर्ट से जमानत मिलने के बाद चार आरोपी बुधवार को जेल से रिहा हो गए. तिहाड़ और मंडोली जेल से बाहर निकलते ही परिजनों ने माला पहनाकर और मिठाई खिलाकर उनका इस्तकबाल किया.', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/695f2067a5704-delhi-riots-gulfisha-fatima-081131587-16x9.jpg', 'https://www.aajtak.in/india/delhi/story/delhi-riots-case-gulfisha-fatima-four-others-released-from-jail-supreme-court-bail-mdsb-ntc-dskc-2433281-2026-01-08', 'Aajtak.in', '2026-01-08 03:13:14', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(95, 1, 'Delhi AQI: दिल्ली में प्रदूषण और कोहरे का डबल अटैक: AQI 400 पार; घने कोहरे ने फ्लाइट्स और ट्रेनों पर लगाया ब्रेक', 'Delhi AQI Today: आज गुरुवार, 8 जनवरी की सुबह दिल्ली-NCR के निवासियों के लिए \'दोहरी मार\' लेकर आई है। एक तरफ कड़ाके की ठंड और घने कोहरे ने विजिबिलिटी को शून्य के करीब पहुंचा दिया है, तो दूसरी तरफ जहरीली हवा ने हेल्थ इमरजेंसी जैसी स्थिति पैदा कर दी है। मौसम विभा…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-AQI-404-Struggles-with-Poor-Visibility.jpg', 'https://hindi.moneycontrol.com/india/delhi-ncr-pollution-aqi-today-8-january-air-quality-chokes-under-hazardous-air-imd-issues-yellow-alert-dense-fog-article-2333442.html', 'Moneycontrol', '2026-01-08 01:59:44', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(96, 1, '\'भारत ट्रंप को संदेश भेजे कि...\', वेनेजुएला के बाद क्यूबा पर संकट, आया राजदूत का बयान', 'वेनेजुएला के बाद ट्रंप की सख्ती से क्यूबा भी दबाव में है. भारत में क्यूबा के राजदूत ने आरोप लगाया है कि ट्रंप प्रशासन दूसरे कार्यकाल में भी क्यूबा को आर्थिक रूप से घेरने की रणनीति पर काम कर रहा है. हर हफ्ते नए प्रतिबंध, सप्लाई रोकने और अलग-थलग करने की कोशिशों…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/695e5d6f93cdd-trump-says-pm-modi-is-unhappy-with-him-over-steep-tariffs-072108275-16x9.png', 'https://www.aajtak.in/world/story/cuba-ambassador-to-india-juan-carlos-attacks-us-donald-trump-ntc-vhrw-dskc-2433057-2026-01-07', 'Aajtak.in', '2026-01-07 13:21:12', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(97, 1, 'धतूरे के लड्डू, गला घोंटकर ट्रिपल मर्डर और थाने में सरेंडर… एक बेटे ने ऐसे उजाड़ दिया अपना पूरा परिवार', 'दिल्ली के लक्ष्मी नगर में सनसनीखेज ट्रिपल मर्डर मामला हर तरह चर्चा का विषय बना हुआ है, जहां एक बेटे ने पहले अपनी मां, बहन और नाबालिग भाई को धतूरे के लड्डू खिलाए और फिर उनकी सबकी गला घोंटकर हत्या कर दी. कहानी यहीं खत्म नहीं होती, इसके बाद कातिल खुद पुलिस थाने …', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/695e42ad6177a-triple-murder-072527280-16x9.jpg', 'https://www.aajtak.in/crime/police-and-intelligence/story/laxmi-nagar-triple-murder-datura-laddoo-delhi-inside-story-ntcpvz-dskc-2432953-2026-01-07', 'Aajtak.in', '2026-01-07 11:27:02', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(98, 1, 'आतिशी के बयान पर बवाल... BJP ने स्पीकर को लिखा पत्र, कहा- सदस्यता की जाए रद्द', 'यह विवाद गुरु तेग बहादुर के 350वें शहीदी वर्ष के अवसर पर दिल्ली विधानसभा में हुई विशेष चर्चा से जुड़ा है. बीजेपी का आरोप है कि आतिशी ने गुरु तेग बहादुर का अपमान किया है. इसे लेकर बीजेपी मंत्री मनजिंदर सिरसा ने दिल्ली विधानसभा अध्यक्ष विजेंद्र गुप्ता को औपचारि…', 'https://akm-img-a-in.tosshub.com/aajtak/images/story/202601/695e3daa527cc-delhi-assembly-lop-and-aap-leader-atishi-070404645-16x9.png', 'https://www.aajtak.in/india/delhi/story/atishi-remark-guru-tegh-bahadur-sirsa-letter-delhi-assembly-speaker-ntc-rlch-dskc-2432960-2026-01-07', 'Aajtak.in', '2026-01-07 11:08:44', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(99, 1, 'बांग्लादेश में कट्टरपंथियों को \'प्रोटेक्शन मनी\' देने को मजबूर हिंदू, फिर भी पत्रकार की कर दी हत्या', 'Hindu Journalist Shot In Bangladesh: एक रिपोर्ट के अनुसार, बांग्लादेश के जेस्सोर जिले में अपनी आइस फैक्ट्री के पास गोली मारकर हत्या किए गए पत्रकार राणा प्रताप बैरागी \'प्रोटेक्शन मनी\' के नाम पर कट्टरपंथी इस्लामी लोगों को अपनी सुरक्षा के लिए पैसे दे रहे थे। टाइ…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Rana-Pratap-Bairagi.jpg', 'https://hindi.moneycontrol.com/world/hindus-in-bangladesh-are-forced-to-pay-protection-money-to-extremists-yet-a-journalist-was-still-murdered-article-2332747.html', 'Moneycontrol', '2026-01-07 08:53:42', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48'),
(100, 1, 'Delhi Stone Pelting: दिल्ली में मस्जिद के पास अतिक्रमण हटाने के दौरान क्यों हुआ पथराव, दिसंबर में ही MCD ने कर दिया था ऐलान', 'दिल्ली में आज सुबह तड़के एक मस्जिद के पास अतिक्रमण हटाने के अभियान के दौरान हिंसक झड़प हुई। रामलीला मैदान में सैयद फैज इलाही मस्जिद से सटी जमीन पर तोड़फोड़ के दौरान स्थानीय लोगों ने नगर निगम के अधिकारियों और पुलिस टीमों पर पत्थर फेंके। दिल्ली हाई कोर्ट के आदे…', 'https://images.moneycontrol.com/static-hindinews/2026/01/Delhi-Encroachment-Drive.jpg', 'https://hindi.moneycontrol.com/india/delhi-encroachment-drive-stone-pelting-near-a-mosque-timeline-mcd-announced-in-december-police-team-injured-article-2332733.html', 'Moneycontrol', '2026-01-07 07:50:09', 1, '2026-01-24 09:36:48', '2026-01-24 09:36:48');

INSERT INTO `places` (`id`, `city_id`, `category_id`, `slug`, `title`, `image`, `description`, `published_date`, `status`, `created_at`, `updated_at`) VALUES
(2, 1, NULL, 'famos-temple-2', 'Famos temple', 'places/tg39r6OjhpmkLtnzHIK4ufAguXUK381sTgP00AR8.png', '<p>dnsand</p><p>akbsdkasdkajdbkasds</p>', '2026-01-24 00:00:00', 1, '2026-01-24 12:52:15', '2026-01-24 13:02:27'),
(3, 2, NULL, 'art-gallery-3', 'Art Gallery', NULL, '<p>Gallery featuring regional artists.</p>', '2026-01-22 18:42:04', 1, NULL, NULL),
(4, 3, NULL, 'sunset-point-4', 'Sunset Point', NULL, '<p>Beautiful viewpoint with scenic sunsets.</p>', '2026-01-14 18:42:13', 1, NULL, NULL),
(5, 3, NULL, 'heritage-fort-5', 'Heritage Fort', NULL, '<p>Historic fort popular among tourists.</p>', '2026-01-04 18:42:13', 1, NULL, NULL),
(6, 2, NULL, 'riverfront-park-6', 'Riverfront Park', NULL, '<p>Green park along the riverfront.</p>', '2025-12-25 18:42:13', 1, NULL, NULL),
(7, 3, NULL, 'mountain-cafe-7', 'Mountain Cafe', NULL, '<p>Cafe with panoramic hill views.</p>', '2026-01-19 18:42:13', 1, NULL, NULL),
(8, 2, NULL, 'lakeside-temple-8', 'Lakeside Temple', NULL, '<p>Peaceful temple by the lake.</p>', '2026-01-09 18:42:13', 1, NULL, NULL),
(9, 1, NULL, 'city-museum-9', 'City Museum', NULL, '<p>Museum showcasing local history.</p>', '2025-12-30 18:42:13', 1, NULL, NULL),
(10, 1, NULL, 'botanical-garden-10', 'Botanical Garden', NULL, '<p>Garden with diverse flora.</p>', '2026-01-21 18:42:13', 1, NULL, NULL),
(11, 2, NULL, 'old-bazaar-11', 'Old Bazaar', NULL, '<p>Traditional market with local crafts.</p>', '2026-01-12 18:42:13', 1, NULL, NULL),
(12, 3, NULL, 'skyline-restaurant-12', 'Skyline Restaurant', NULL, '<p>Rooftop dining with skyline views.</p>', '2026-01-17 18:42:13', 1, NULL, NULL),
(13, 3, NULL, 'art-gallery', 'Art Gallery', 'places/juV4i6Kz2xdYcNfFlNjuW4wy5cdHrXCQVacFIRev.png', '<p>Gallery featuring regional artists. asdjahdjhd</p><p>adadaskdaskhdks</p>', '2026-01-22 00:00:00', 1, NULL, '2026-01-24 15:36:38'),
(14, 1, NULL, 'sunset-point-14', 'Sunset Point', NULL, '<p>Beautiful viewpoint with scenic sunsets.</p>', '2026-01-14 18:43:03', 1, NULL, NULL),
(15, 1, NULL, 'heritage-fort-15', 'Heritage Fort', NULL, '<p>Historic fort popular among tourists.</p>', '2026-01-04 18:43:03', 1, NULL, NULL),
(16, 1, NULL, 'riverfront-park-16', 'Riverfront Park', NULL, '<p>Green park along the riverfront.</p>', '2025-12-25 18:43:03', 1, NULL, NULL),
(17, 3, NULL, 'mountain-cafe-17', 'Mountain Cafe', NULL, '<p>Cafe with panoramic hill views.</p>', '2026-01-19 18:43:03', 1, NULL, NULL),
(18, 3, NULL, 'lakeside-temple-18', 'Lakeside Temple', NULL, '<p>Peaceful temple by the lake.</p>', '2026-01-09 18:43:03', 1, NULL, NULL),
(19, 1, NULL, 'city-museum-19', 'City Museum', NULL, '<p>Museum showcasing local history.</p>', '2025-12-30 18:43:03', 1, NULL, NULL),
(20, 2, NULL, 'botanical-garden-20', 'Botanical Garden', NULL, '<p>Garden with diverse flora.</p>', '2026-01-21 18:43:03', 1, NULL, NULL),
(21, 3, NULL, 'old-bazaar-21', 'Old Bazaar', NULL, '<p>Traditional market with local crafts.</p>', '2026-01-12 18:43:03', 1, NULL, NULL),
(22, 3, NULL, 'skyline-restaurant-22', 'Skyline Restaurant', NULL, '<p>Rooftop dining with skyline views.</p>', '2026-01-17 18:43:03', 1, NULL, NULL),
(23, 1, NULL, 'art-gallery-23', 'Art Gallery', NULL, '<p>Gallery featuring regional artists.</p>', '2026-01-22 18:43:04', 1, NULL, NULL);

INSERT INTO `sessions` (`id`, `user_id`, `ip_address`, `user_agent`, `payload`, `last_activity`) VALUES
('kn2eXKHcRaNalksrAQl7Yp2EsF5Vt2HIvLOFg0i9', 2, '127.0.0.1', 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/144.0.0.0 Safari/537.36', 'YTo0OntzOjY6Il90b2tlbiI7czo0MDoiNkRvVXNEN0lWV0J0ZlZUSEJPbGpDdlBESWNIVmlhd2JNTnRJeFg3eSI7czo5OiJfcHJldmlvdXMiO2E6Mjp7czozOiJ1cmwiO3M6MjQ6Imh0dHA6Ly9pbmRpYW5jaXRpZXMudGVzdCI7czo1OiJyb3V0ZSI7czo0OiJob21lIjt9czo2OiJfZmxhc2giO2E6Mjp7czozOiJvbGQiO2E6MDp7fXM6MzoibmV3IjthOjA6e319czo1MDoibG9naW5fd2ViXzU5YmEzNmFkZGMyYjJmOTQwMTU4MGYwMTRjN2Y1OGVhNGUzMDk4OWQiO2k6Mjt9', 1769271824);

INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
(1, 'Test User', 'test@example.com', '2025-12-06 10:23:58', '$2y$12$211d0Esc/bAHtUz9WX2lwutazqs0sJmfIkuE9YCms8r.5P1IcvZcq', 'n3ZdNRJKSS', '2025-12-06 10:23:59', '2025-12-06 10:23:59'),
(2, 'Test User', 'news@admin.com', '2025-12-08 10:52:54', '$2y$12$7M9K7JYvP3zooXzpcmZS/O1KQ6suKfcAghUZG9Was/vqFskx262OK', 'KVEKvPu7MnADdfVSF54LqpvCSDPshPom9l28SNnKXJyfc0ssU7N2slcDMrYc', '2025-12-08 10:52:56', '2025-12-08 10:52:56');

INSERT INTO `videos` (`id`, `city_id`, `title`, `youtube_url`, `description`, `status`, `created_at`, `updated_at`) VALUES
(1, 2, 'लखनऊ की शान: एक अविस्मरणीय सफर', 'https://youtu.be/3QHoMnuSMUY?si=9RphUNrb6vWMFKgR', 'यह आगरा शहर का एक 4K सिनेमैटिक और जानकारी भरा वीडियो है। आगरा शहर को ताजमहल का शहर भी कहा जाता है। इस वीडियो में आपको आगरा में घूमने की जगहों की झलक मिलेगी, जिसमें आगरा की ऐतिहासिक जगहें शामिल हैं। इस वीडियो में सिनेमैटिक मोड में हिंदी वॉयस-ओवर के साथ आगरा शहर के फैक्ट्स और आगरा शहर की डिटेल्स भी शामिल हैं।', 1, '2025-12-09 10:51:51', '2025-12-09 10:51:51'),
(2, 1, 'नवाबों का शहर: लखनऊ की कहानी...', 'https://youtu.be/aHMG790DzHQ?si=EdBnDkVHf2-QEW51', 'लखनऊ के पॉश इलाके में एक महिला के साथ घिनौना अत्याचार हुआ, जिसे मोहल्ले के लोग तमाशा बनाकर देखते रहे.यह कहानी सिर्फ सड़क पर हुए हमले की नहीं, बल्कि 5 साल तक चले शोषण, शादी का झांसा, जबरन गर्भपात और धमकियों की भी है.डीसीपी ईस्ट के अनुसार मुकदमा दर्ज कर लिया गया, लेकिन अब तक गिरफ्तारी या सख्ती नहीं दिखी. यह वीडियो उठाता है सवाल — क्या इंसानियत सिर्फ ऑनलाइन दिखती है या वास्तविक जीवन में?\r\nदेखिए यूपी तक की रिपोर्ट और जानिए लखनऊ के इस क्राइम का पूरा सच', 1, '2025-12-09 10:54:02', '2025-12-09 10:54:02'),
(3, 1, 'नवाबों का शहर: लखनऊ की कहानी...', 'https://youtu.be/aHMG790DzHQ?si=EdBnDkVHf2-QEW51', 'लखनऊ के पॉश इलाके में एक महिला के साथ घिनौना अत्याचार हुआ, जिसे मोहल्ले के लोग तमाशा बनाकर देखते रहे.यह कहानी सिर्फ सड़क पर हुए हमले की नहीं, बल्कि 5 साल तक चले शोषण, शादी का झांसा, जबरन गर्भपात और धमकियों की भी है.डीसीपी ईस्ट के अनुसार मुकदमा दर्ज कर लिया गया, लेकिन अब तक गिरफ्तारी या सख्ती नहीं दिखी. यह वीडियो उठाता है सवाल — क्या इंसानियत सिर्फ ऑनलाइन दिखती है या वास्तविक जीवन में?\r\nदेखिए यूपी तक की रिपोर्ट और जानिए लखनऊ के इस क्राइम का पूरा सच', 1, '2025-12-09 10:54:02', '2025-12-09 10:54:02'),
(4, 1, 'नवाबों का शहर: लखनऊ की कहानी...', 'https://youtu.be/aHMG790DzHQ?si=EdBnDkVHf2-QEW51', 'लखनऊ के पॉश इलाके में एक महिला के साथ घिनौना अत्याचार हुआ, जिसे मोहल्ले के लोग तमाशा बनाकर देखते रहे.यह कहानी सिर्फ सड़क पर हुए हमले की नहीं, बल्कि 5 साल तक चले शोषण, शादी का झांसा, जबरन गर्भपात और धमकियों की भी है.डीसीपी ईस्ट के अनुसार मुकदमा दर्ज कर लिया गया, लेकिन अब तक गिरफ्तारी या सख्ती नहीं दिखी. यह वीडियो उठाता है सवाल — क्या इंसानियत सिर्फ ऑनलाइन दिखती है या वास्तविक जीवन में?\r\nदेखिए यूपी तक की रिपोर्ट और जानिए लखनऊ के इस क्राइम का पूरा सच', 1, '2025-12-09 10:54:02', '2025-12-09 10:54:02'),
(5, 1, 'नवाबों का शहर: लखनऊ की कहानी...', 'https://youtu.be/aHMG790DzHQ?si=EdBnDkVHf2-QEW51', 'लखनऊ के पॉश इलाके में एक महिला के साथ घिनौना अत्याचार हुआ, जिसे मोहल्ले के लोग तमाशा बनाकर देखते रहे.यह कहानी सिर्फ सड़क पर हुए हमले की नहीं, बल्कि 5 साल तक चले शोषण, शादी का झांसा, जबरन गर्भपात और धमकियों की भी है.डीसीपी ईस्ट के अनुसार मुकदमा दर्ज कर लिया गया, लेकिन अब तक गिरफ्तारी या सख्ती नहीं दिखी. यह वीडियो उठाता है सवाल — क्या इंसानियत सिर्फ ऑनलाइन दिखती है या वास्तविक जीवन में?\r\nदेखिए यूपी तक की रिपोर्ट और जानिए लखनऊ के इस क्राइम का पूरा सच', 1, '2025-12-09 10:54:02', '2025-12-09 10:54:02'),
(6, 1, 'नवाबों का शहर: लखनऊ की कहानी...', 'https://youtu.be/aHMG790DzHQ?si=EdBnDkVHf2-QEW51', 'लखनऊ के पॉश इलाके में एक महिला के साथ घिनौना अत्याचार हुआ, जिसे मोहल्ले के लोग तमाशा बनाकर देखते रहे.यह कहानी सिर्फ सड़क पर हुए हमले की नहीं, बल्कि 5 साल तक चले शोषण, शादी का झांसा, जबरन गर्भपात और धमकियों की भी है.डीसीपी ईस्ट के अनुसार मुकदमा दर्ज कर लिया गया, लेकिन अब तक गिरफ्तारी या सख्ती नहीं दिखी. यह वीडियो उठाता है सवाल — क्या इंसानियत सिर्फ ऑनलाइन दिखती है या वास्तविक जीवन में?\r\nदेखिए यूपी तक की रिपोर्ट और जानिए लखनऊ के इस क्राइम का पूरा सच', 1, '2025-12-09 10:54:02', '2025-12-09 10:54:02');



/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;